### ISSUE TITLE
Selecting frames efficiently with VideoDecoder

### ISSUE THREAD

**Issue by dooplecks** [w3c/webcodecs#123]
Given a video file and a timestamp, we want to be able to select (decode until we reach) the frame at that particular time.

With libavcodec, we can decode packets until we get the frame we want, i.e. call `avcodec_send_packet(ctx, pkt)` and `avcodec_receive_frame(ctx, frame)` until `frame` lies on our timestamp. We decode no more data than necessary, and we can continue to decode more frames from that point in time if need be.

With WebCodecs, calling `decode(chunk)` may produce a frame at some indeterminate time in the future via the output callback. Because of this, there is no way to determine when to stop calling `decode`. We can see if the provided chunks produced the desired frame or not by `flush`ing, but this wastes work by resetting the decoder, making subsequent delta chunks unusable.

Is there some way to accomplish this efficiently with WebCodecs presently?

**Comment by sandersdan** [comment]
Most decoders do not provide bounded latency on decoding, but in practice this is mostly to account for reordering and post-processing operations.

In Chrome's implementation, the behavior does vary. The macOS hardware decoder will output all frames that were input, while the FFmpeg software decoder requires either one extra chunk or a `flush()`. Note though [crbug.com/1168572](https://bugs.chromium.org/p/chromium/issues/detail?id=1168572).

I'd recommend monitoring |decodeQueueSize| and pushing in more chunks only when it is low.

There is a lot of room to improve the backpressure mechanisms in WebCodecs, although the priority is low in the short term.

**Comment by chcunningham** [comment]
I think the previous comment completely answers the question. Please re-open in more to discuss.
