### ISSUE TITLE
AV1 encoder config

### ISSUE THREAD

**Issue by pinkywon777** [w3c/webcodecs#147]
Hi! I am trying to configure an av1 encoder, using codec "av01.0.01M.08" in chrome 90 browser. I got error msg"DOMException: Failed to execute 'configure' on 'VideoEncoder': Unsupported codec type.
    at HTMLButtonElement.<anonymous> (file:///Users/pingw/Downloads/src/index.html:108:24)"

Based on Chrome 90 description(https://www.chromestatus.com/feature/6206321818861568), the av1 encoding should be supported, can any one help me to resolve this?

**Comment by chcunningham** [comment]
Hi @pinkywon777 - the AV1 encoder is supported by Chrome's WebRTC stack, but we haven't yet added the connection to WebCodecs. But we definitely plan to!

**Comment by aboba** [comment]
@pinkywon777 The Chrome Status entry is referring to implementation of the [AV1 RTP Payload format ](https://aomediacodec.github.io/av1-rtp-spec/)within WebRTC.

**Comment by chcunningham** [comment]
Closing this, as I don't think there's any spec work to take on here. Adding support for AV1 encoding is a UA specific decision (not required by spec). For Chrome, I've filed https://bugs.chromium.org/p/chromium/issues/detail?id=1208280

**Comment by padenot** [comment]
Modulo needing an addition to the registry, yes.
