### ISSUE TITLE
Is there a way to keep and process chunks in WASM only

### ISSUE THREAD

**Issue by sumeet-tiwari-samespace** [w3c/webcodecs#148]
If we pass a WASM function as the callback to the encoder, will it be good for my performance or will it not make any difference.

**Comment by chcunningham** [comment]
I expect it wouldn't make any difference. @ecmziegler to confirm

**Comment by padenot** [comment]
How would that work? https://github.com/WebAssembly/design/issues/1162 isn't solved, so there is a copy, so it's slower. Of course then you can use WASM to process the encoded packet, but this really is orthogonal to Web Codecs.

**Comment by aboba** [comment]
@sumeet-tiwari-samespace Applications which formerly used WASM for video encode/decode are moving to WebCodecs, because of the improved performance. So while WASM is viable for audio encode/decode, it will not improve performance in video encode/decde, even with WASM SIMD and a Dedicated Worker.

**Comment by padenot** [comment]
I think this is about post-processing the packets/frames in WASM, right ? Not really encoding/decoding in WASM.

**Comment by sumeet-tiwari-samespace** [comment]
yes @padenot

**Comment by padenot** [comment]
Then I'd just say that it works today, but it might work better at some point if/when https://github.com/WebAssembly/design/issues/1162 is designed and implemented and shipped.

Because this is not a Web Codecs issues, I'm closing this, but please feel free to open more issues if needed. Thanks!
