### ISSUE TITLE
Make VideoFrame a CanvasImageSource

### ISSUE THREAD

**Issue by chcunningham** [w3c/webcodecs#158]
Already [implemented](https://chromium-review.googlesource.com/c/chromium/src/+/2680955) in Chrome. This issue tracks the need to file a PR on HTML to get VideoFrame added [here](https://html.spec.whatwg.org/multipage/canvas.html#canvasimagesource).

This makes it possible to use canvas drawImage(videoFrame) as well as window.createImageBitmap(videoFrame) (meaning we can remove videoFrame.createImageBitmap().

This is simpler to use and more efficient vs previous proposal of always first creating an ImageBitmap. 

Related issues: #88 and #145

**Comment by chcunningham** [comment]
@domenic FYI

**Comment by dalecurtis** [comment]
We also need to add it as a TexImageSource here: https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14 I was planning to get to it this week.

**Comment by Daddy2200** [comment]
![222C9443-AAF3-4642-9603-282D9D6D6B9C](https://user-images.githubusercontent.com/81929259/115135752-00875e80-9fe9-11eb-991a-18f23e49de41.jpeg)
![837866C9-51E9-43AB-87EA-E055849563C3](https://user-image@hidde 
![19EC701F-3E5E-4DEB-9166-B0E15F85853D](https://user-images.githubusercontent.com/81929259/115135760-05e4a900-9fe9-11eb-9cad-ff1eca220b9b.jpeg)
![B3B0763B-70A0-44F1-8749-2324F316EE95](https://user-images.githubusercontent.com/81929259/115135761-067d3f80-9fe9-11eb-8871-09f6f3af9c84.jpeg)
![18FB2D84-50D4-4674-99E0-CE71ACA71662](https://user-images.githubusercontent.com/81929259/115135762-0715d600-9fe9-11eb-9c01-180f941319c7.jpeg)


.githubusercontent.com/81929259/115135753-02512200-9fe9-11eb-80c6-4fcd014f7951.jpeg)
@
![773F0255-1A96-48F7-B0D4-2EEB68002793](https://user-images.githubusercontent.com/81929259/115135754-02e9b880-9fe9-11eb-98b2-744e01eb7a2d.jpeg)
![D42DEDD1-6987-4068-928C-62CD8AD97AE2](https://user-images.githubusercontent.com/81929259/115135755-03824f00-9fe9-11eb-996a-a543d9849228.jpeg)
![E320436E-2951-4CEC-A41C-9B173BE9B6BD](https://user-images.githubusercontent.com/81929259/115135756-041ae580-9fe9-11eb-8862-28991af7c35e.jpeg)
![C2D0F30C-7D14-45B0-AD5F-C7B93B058082](https://user-images.githubusercontent.com/81929259/115135758-041ae580-9fe9-11eb-9870-bb591f3ab4f8.jpeg)
![08231013-EC78-453A-8BB9-104CD9EEF582](https://user-images.githubusercontent.com/81929259/115135759-054c1280-9fe9-11eb-86dc-cdec761225ef.jpeg)
