### ISSUE TITLE
Add [EnforceRange] to IDL numeric types

### ISSUE THREAD

**Issue by chcunningham** [w3c/webcodecs#160]
EnforceRange causes TypeError for values outside the range of the idl type (e.g. -1 for unsigned long -> TypeError) rather than clamping to a valid value. 

Chromium has implemented this here
https://chromium-review.googlesource.com/c/chromium/src/+/2792742

**Comment by chcunningham** [comment]
triage note: marking 'editorial' as we have consensus on what to do, and chrome has done it. We just need to update the spec

**Comment by padenot** [comment]
This is breaking, then, but I agree it's quite easy.
