### ISSUE TITLE
Add API for changing metadata

### ISSUE THREAD

**Issue by sandersdan** [w3c/webcodecs#161]
An app may have a frame (video or audio) but want to change its metadata (timestamp, duration, colorspace) before passing it to another component. I propose that we extend `clone()` to take an initialization dictionary that allows this metadata to be overwritten in the clone. It would probably make sense for any introduced `copy()` API to do the same.

**Comment by padenot** [comment]
Having the capability to do this would be very useful. With copy-on-write semantics your API suggestion sounds fine in terms of performance, but maybe a bit unfamiliar to developers.

**Comment by chcunningham** [comment]
Triage note: marked 'extension' as the proposal is describing adding new arguments to a method.

**Comment by padenot** [comment]
I tend to agree in practice, but this is breaking in theory (`.length` on the method changes).

**Comment by sandersdan** [comment]
Note: now that we support construction from a `CanvasImageSource`, and `VideoFrame` is a `CanvasImageSource`, this can be written as `new VideoFrame(originalFrame, { /* new metadata */ }`, and Chrome's implementation already supports overriding a timestamp in this way.

I think it may be surprising that this construction clones rather than copies, but the spec is already quite clear on this point.

Maybe we don't actually need `clone()` at all?

**Comment by chcunningham** [comment]
@sandersdan what are your feelings as of late? Do you want to see metadata overrides added to clone() or is the VideoFrame constructor option sufficient? I can see it either way (i.e. symmetry is nice, but argument could also be made that clone() is the "simple" option).

**Comment by sandersdan** [comment]
I no longer feel strongly about `copy()` and `clone()` supporting these options. It would presumably be trivial to support that use, but the added complexity in teaching the API is probably not worth it.

I suppose there is also the inverse to consider, an option for `new VideoFrame()` to force copy semantics. This has the advantage of actually highlighting the default clone behavior, but of course is not async which likely is a showstopper.

**Comment by chcunningham** [comment]
Ok, lets close this for now. If we hear folks hate the current options we'll reconsider.
