### ISSUE TITLE
Web IDL validation errors

### ISSUE THREAD

**Issue by autokagami** [w3c/webcodecs#164]
🤖 This is an automatic issue report for Web IDL validation error. 🤖

The bot found validation errors but couldn't fix them automatically, since the IDL texts include HTML tags. Please check the following messages and fix them.

* ```
  Validation error at line 2 in webcodecs,20, inside `interface Plane`:
  interface Plane {
            ^
  ```
  
  > Error: Interfaces must have `[Exposed]` extended attribute. To fix, add, for example, `[Exposed=Window]`. Please also consider carefully if your interface should also be exposed in a Worker scope. Refer to the [WebIDL spec section on Exposed](https://heycam.github.io/webidl/#Exposed) for more information.

Please file an issue at https://github.com/saschanaz/webidl-updater/issues/new if you think this is invalid or should be enhanced.

**Comment by saschanaz** [comment]
Is there any good reason to have `<xmp>` inside `<pre class='idl'>`? I think they are redundant, no?
