### ISSUE TITLE
"Cannot call 'decode' on a closed codec" error

### ISSUE THREAD

**Issue by fnandoz21** [w3c/webcodecs#181]
I am trying to create an EncodedVideoChunk and then immediately decode this chunk, similar to shown below:
`const response = fetch(url)
            .then(
              (response) =>
                new EncodedVideoChunk({
                  type: "key",
                  timestamp: timestamp,
                  data: new Uint8Array(response.body),
                })
            )
            .then((chunk) => decoder.decode(chunk));`

However, the very last line throws an error I don't know how to address. I screenshotted it below:
![image](https://user-images.githubusercontent.com/58253328/114797814-facc1780-9d61-11eb-9723-9b999b7dfe07.png)

If someone could help me address this, I would greatly appreciate it. Thanks.

**Comment by aboba** [comment]
@frnandoz21 Can you provide some of the code before the snippet (e.g. where you initialize and configure the decoder and encoder)?

**Comment by fnandoz21** [comment]
This code takes in data that has already been encoded so no encoder is initialized here. Here is the code for the decoder though:
`function createDecoder() {
        let ready_frames = [];

        function handleFrame(frame) {
          ready_frames.push(frame);
          console.log("Received Frame");
        }

        const init = {
          output: handleFrame,
          error: (e) => {
            console.log(e.message);
          },
        };

        const config = {
          codec: codec_string,
          codedWidth: imageWidth,
          codedHeight: imageHeight,
        };

        let decoder = new VideoDecoder(init);
        decoder.configure(config);
        return decoder;
      }`

**Comment by aboba** [comment]
@fnandoz21 In `createDecoder()` , you might add a line "console.log(decoder.state);" prior to returning, in order to make sure that `decoder.configure(config);` was successful.  I suspect you'll find the `state` to be "closed".

**Comment by chcunningham** [comment]
Also, check to see if you have a log from your init error callback. Something about the config is probably unsupported... hopefully the log hints at what. You can call VideoDecoder.isConfigSupported(config) to check for support prior to calling configure().

**Comment by chcunningham** [comment]
@fnandoz21, were the above suggestions helpful?

**Comment by chcunningham** [comment]
No response from reporter. Please re-open if needed.
