### ISSUE TITLE
Extending Metadata

### ISSUE THREAD

**Issue by aboba** [w3c/webcodecs#182]
Issue opened at the request of Youenn Fablet, who is looking to extend metadata for use in the Insertable Streams specs, which reuse (VideoFrame, encodedVideoChunk, etc.) from WebCodecs.

The additional Metadata in question would be things like CSRCs and the SSRC which are RTP specific and therefore do not make sense in WebCodecs (but would be useful in WebRTC Insertable Streams). But it does raise issues relating to metadata mutability (See Issue https://github.com/w3c/webcodecs/issues/161).

**Comment by chcunningham** [comment]
I think Youenn filed a duplicate issue, #189. Closing this one in favor of that.
