### ISSUE TITLE
MediaStreamTrackProcessor -> WebCodecs

### ISSUE THREAD

**Issue by chcunningham** [w3c/webcodecs#191]
In the recent editors call, @aboba mentioned receiving questions on using MediaStreamTrackProcessor w/ WebCodecs. We have [some code demonstrating this in the explainer](https://github.com/w3c/webcodecs/blob/main/explainer.md#example-of-real-time-communication). Maybe its just a matter of sharing that more broadly? Or is there some aspect of the integration we need to highlight? 

The explainer is somewhat psuedo-code, so I've made a [similar demo here](https://mstp-to-videoencoder.glitch.me/mstp-to-videoencoder.html) that folks can actually run in Chrome Canary (92). 

The code looks like this
```javascript
// Setup trackProcessor to grab every VideoFrame from the camera
let stream = await navigator.mediaDevices.getUserMedia({
  audio: false,
  video: true
});
let trackProcessor = new MediaStreamTrackProcessor(
  stream.getVideoTracks()[0]
);

// Log encoder outputs. A real app would do something like send to a remote peer.
function handleChunk(chunk, metadata) {
  console.log("handleChunk( timestamp=" + chunk.timestamp + " )");
}

// Setup VideoEncoder
let videoEncoder = new VideoEncoder({
  output: handleChunk,
  error: e => {
    console.log(e.message);
  }
});

// Read frames and encode()!
const reader = trackProcessor.readable.getReader();
while (true) {
  const { done, value } = await reader.read();

  if (done) return;

  if (videoEncoder.state == "unconfigured") {
    videoEncoder.configure({
      codec: "vp8",
      width: value.cropWidth,
      height: value.cropHeight
    });
  }

  videoEncoder.encode(value);
  value.close();
}
```

**Comment by aboba** [comment]
@chcunningham The main questions have related to `writableControl`. From the sample, it would appear that this doesn't need to be hooked up. Is there any situation in which it would be useful to do something with it?

**Comment by chcunningham** [comment]
WebCodecs users are free to entirely ignore writableControl. They may opt-in to sending control signals if they find them useful. 

Currently the only control signal is "request-frame". I'm guessing this is used when you need a new frame on-demand from a low fps stream (@guidou @alvestrand, do I have that right?). If so, WebCodecs users could send that signal if needed a frame. The camera's I've tested with push frames at a steady 20-30fps, so I've not needed this.

@alvestrand mentioned that they may eventually define a signal that allows request a different frame size from the camera. This could be useful if apps are adapting to congestion or viewport size changes.

**Comment by guidou** [comment]
You are totally right, both about control signals being an opt-in mechanism
and about "request-frame" being used to request a new frame on demand from
a low-fps stream.
For example, a screen capturer capturing a presentation may not produce any
frames while a presentation is not changing. In these cases, peer
connections sometimes need to send extra frames as part of their protocol
and send this signal to the screen capturer.

**Comment by aboba** [comment]
One other question that came up today in the editor's meeting. Is there a way to reuse buffers, rather than continually allocating/freeing them?

**Comment by padenot** [comment]
> One other question that came up today in the editor's meeting. Is there a way to reuse buffers, rather than continually allocating/freeing them?

This is now being discussed in https://github.com/w3c/webcodecs/issues/212

**Comment by chcunningham** [comment]
I think we can track the remaining question in #212. Feel free to re-open if more to discuss.

**Comment by padenot** [comment]
https://jan-ivar.github.io/polyfills/mediastreamtrackprocessor.js is a polyfill written by us that you can use. We're planning to implement `MediaStreamTrackProcessor`, video-only, worker-only (as it's the only thing that has been agreed upon).

**Comment by vitaly-castLabs** [comment]
@padenot Brilliant! Hugely appreciated! I had to remove the curly brackets from `constructor({track})` to make it work, just FYI.

I suspected I had to something like that - not pretty performance-wise, but does the job for now for Safari (works pretty well actually) and Firefox (probably not fast enough and causes the encoder to compress the heck out of it, combined with very low frame rate):
https://vitaly-castlabs.github.io/webcodecs-mse-player/

**Comment by jan-ivar** [comment]
Chrome works with or without the curly brackets but they're needed per [per spec](https://w3c.github.io/mediacapture-transform/#track-processor-interface).

Glad you got it working! Not sure what's up with the encoder. This (unencoded) [demo](https://jsfiddle.net/jib1/2gdkc7ew) seems to run well for me in Firefox.

**Comment by vitaly-castLabs** [comment]
You're right, it was the problem of the original code calling the MSTP constructor wrong: https://github.com/vitaly-castLabs/webcodecs-mse-player/commit/183504a0a108b00ccfca31017df91801879a7d4a

**Comment by vitaly-castLabs** [comment]
One more thing. @jan-ivar shouldn't `controller.enqueue(new VideoFrame(canvas, {timestamp: t1}))` use `t1 * 1000` instead? `performance.now()` returns milliseconds which need to be converted to microseconds. I'm definitely getting wrong timestamps in Firefox...
