### ISSUE TITLE
webrtc and webcodec hardware VideoFrame no planes

### ISSUE THREAD

**Issue by IEturbo** [w3c/webcodecs#192]
![image](https://user-images.githubusercontent.com/25050386/116034464-e2c79280-a695-11eb-97e6-ec9e4168cd6c.png)

When I use webrtc combined with webcodec in Chrome, there is VideoFrame no planes data in hardware decoding for a period of time. It is normal to turn off hardware decoding and use software decoding. Is this a bug, or am I using it improperly?  thanks

**Comment by sandersdan** [comment]
This is normal (for Chrome's implementation of WebCodecs), but we are working on a new async readback API (#157) that will not have this limitation.

As a workaround, you can `createImageBitmap(videoFrame)` and read from that.

**Comment by chcunningham** [comment]
Please re-open if there are follow up questions.
