### ISSUE TITLE
Image encoding API

### ISSUE THREAD

**Issue by padenot** [w3c/webcodecs#204]
#152 is the initial PR adding image decoding support, but image encoding needs to be added to the spec.

**Comment by dalecurtis** [comment]
Seems reasonable, the existing image encoding path only operates on canvas:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

**Comment by dalecurtis** [comment]
Feel free to leave that comment on the linked issue! FWIW, you can assemble an aPNG from multiple toBlob(png) calls IIUC.

**Comment by dalecurtis** [comment]
Since I was curious if it could actually be done, here's a demo assembling an APNG from PNG files for those curious: https://dalecurtis.github.io/apng-assemble/ 
https://github.com/dalecurtis/dalecurtis.github.io/tree/master/apng-assemble

**Comment by talltyler** [comment]
Thank you, this is truly very helpful. 
I still think having an ImageEncoder could with a common interface that could make use of VideoFrames could be even more useful but for now this is better than what I'm currently doing.

**Comment by aboba** [comment]
@Djuffin @padenot Can we close this?

**Comment by Djuffin** [comment]
No progress and no plans on this issue for 3 years.
