### ISSUE TITLE
Add optimizeForLatency boolean flag to VideoDecoderConfig.

### ISSUE THREAD

**Issue by dalecurtis** [w3c/webcodecs#206]
Some software decoders are optimized for throughput rather than latency via frame threading. We should provide a hint that a client prefers lower latency versus throughput.

Without this hint some configurations would require a client to call flush() after every decode() call to ensure they get a frame.

**Comment by padenot** [comment]
Fully agree. To some extent, this is also related to software vs. hardware encoder choice in common setups.

**Comment by chcunningham** [comment]
Editors call: concept looks good. @padenot @aboba : pls bikeshed on name w/ priority

**Comment by dalecurtis** [comment]
Bike shed colors:
 * lowLatency : bool
 * optimizeForLowLatency : bool
 * lowDelay : bool
 * optimizeForLowDelay : bool

I don't have any strong preference. We call it low delay mode internally.

**Comment by marcello3d** [comment]
AudioContext calls it "latencyHint": https://developer.mozilla.org/en-US/docs/Web/API/AudioContextOptions/latencyHint

**Comment by dalecurtis** [comment]
Yeah we also have https://github.com/WICG/media-latency-hint/blob/main/explainer.md but I think those are slightly different than what we're trying to convey here.

**Comment by padenot** [comment]
> lowLatency : bool

this is clear enough and not overly long, I think. I also like `lowDelay`.

Taking a step back, there are going to be lots of configurable switches, codec-specific settings and all that in the registry, but this is such an important, common and well understood switch that (I think) it makes sense to have something non-codec-specific.

**Comment by dalecurtis** [comment]
I'd lean towards `lowDelay` then. The reason. I originally went with `optimizeForLatency` is that `lowDelay` and `lowLatency` don't quite covey the best effort nature of the request. I.e., we don't always have any lee-way with hardware decoders. Would you expect this to be best-effort or should we force software in cases where we aren't sure we can make this guarantee?

Forcing software seems hard, since what hardware decoder can make guarantee this or not is likely a long-tail list.

**Comment by padenot** [comment]
>  Would you expect this to be best-effort or should we force software in cases where we aren't sure we can make this guarantee?

I'm torn, here is how I see things:

Authors can have this information, by using `isConfigSupported` and `"require"` `"deny"` for hardware acceleration, with this new flag passed in, so advanced users that really know what they are doing can always be very specific (which I think is the minimum we can do for a low level API aimed at advanced users), if we make this "non-best-effort". I assume that if a particular set of parameter for `isConfigSupported` is accepted, then the decoding will be able to proceed as such, and not modified. Similarly, if even in software it's not possible to do low-latency (I seem to recall this to be a thing, but I'm not sure), it's best to be explicit, some use-cases really do require low-latency decoding.

This is when the fact that the hardware/software decoder can't do low-latency is known (then we can discuss on what the meaning of low-latency is, I guess, that's an orthogonal issue).

When this is **not** known, we can imagine punting to the implementation to make it known, with an in-UA-benchmark (example from Gecko to return accurate information for `MediaCapabilities`: https://searchfox.org/mozilla-central/source/dom/media/Benchmark.cpp, but this is for throughput and not latency). For us, it's stored locally on the device and periodically updated (say, when decoders are updated).

There is also the case where going low latency requires a software decoder, but the software decoder cannot do enough fps for the video to be useful in real-time (I'm thinking those [Windows 10 laptops](https://www.lenovo.com/fr/fr/laptops/yoga/yoga-2-in-1-series/Yoga-C630-13Q50/p/88YGC601090) based on ARM, that can do vp9 without any issue in hardware but struggle doing it in software, where it's barely possible if at all). So then what should be the answer? Maybe we do want to add something to `MediaCapabilities`, where the API shape lends itself a bit more to this kind of assessment.

So yes, I guess this is hard, but it's possible, so not doing it when it's better to do it is hard to justify, when it unlocks a very clear and measurable benefit for developers and users.

**Comment by dalecurtis** [comment]
Interesting. I like the idea of using `isConfigSupported` but am wary of using an in-UA-test for this since it seems counter to the low level nature of the API. I.e., if this were a native app I'd expect it should use the API to test support on its own for something that can't be answered without a decoding test. I agree that MediaCapabilities feels like a better home for such questions.

Additionally, I think we do have to stray a bit into what low latency means unfortunately :) Nominally I think we're both using it to mean 1-in-1-out, but that behavior can be stream dependent (e.g., b-frames can preclude this behavior). So adding a UA test which just checks a curated stream may be not be the answer an author is looking for.

As such I'm inclined to consider this best effort and ignore it during `isConfigSupported`.

**Comment by chcunningham** [comment]
Triage note: marking 'extension', as this is defining a new attribute.

**Comment by chcunningham** [comment]
> As such I'm inclined to consider this best effort and ignore it during isConfigSupported.

@padenot, thoughts on [Dale's last reply](https://github.com/w3c/webcodecs/issues/206#:~:text=commented-,on%20May%204,-Interesting.%20I%20like)?

**Comment by dalecurtis** [comment]
@padenot are you okay with the `optimizeForLatency` name given the conclusion that it'll function as a hint?

**Comment by padenot** [comment]
Yes, this name sounds good, thanks.
