### ISSUE TITLE
Alpha support

### ISSUE THREAD

**Issue by chcunningham** [w3c/webcodecs#207]
I've been meaning to send a PR for the latest thinking from the Chrome explorations... I'll try to have it out this week. 

Generally, my proposal will be:
* add a `attribute bool hasAlpha` to `VideoFrame`. The semantics for planar formats would be that the last plane (highest index) is the alpha plane. More on this in https://github.com/w3c/webcodecs/issues/200#issuecomment-829535780
* Define an `enum AlphaOption { keep, discard }`, and add attributes/members using this enum to `VideoFrameInit` and `VideoEncoderConfig`. Choose defaults based on expected use cases. 
  * For `VideoEncoderConfig.alpha`, default to `=discard`. Alpha encoding is a thing, but relatively rare. In the event that the `VideoFrame` is backed by a texture, we can use `=discard` to optimize readback to a alpha-less format that is supported by the `VideoEncoder` (e.g. NV12)
  * For `VideoFrameInit.alpha`, default to `=keep`. Seems least disruptive in the event you weren't planning to encode the frame (which is already covered above).
* For `VideoEncoder`, if configured with `alpha=keep` (and if supported), we emit the alpha data as side data in the chunk output callback. This follows the path of existing underlying encoders (e.g. ffmpeg's `AV_PKT_DATA_MATROSKA_BLOCKADDITIONAL`). 
  * The output callback already emits chunk metadata in the form of the `VideoDecoderConfig` needed to decode the chunk. PR #187 is expanding that into a metadata bucket for homing chunk SVC metadata. I propose to just add alpha side data there as well... TBD some naming bikeshed. 

Note: we haven't yet thought about how to do *decoding* of alpha. Something to consider.

**Comment by sandersdan** [comment]
Chrome's implementation has RGBA, BGRA, RGBX, and BGRX. Would this be trimmed down to RGBA and BGRA by your proposal?

**Comment by chcunningham** [comment]
I don't immediately see the value in having the 'X' formats externally. IIUC, they have an alpha channel that conveys no meaningful info (all 255)? If so, I'm inclined to always call RGBX as RGB and so on, and hide the all-255 alpha channel from JS.

**Comment by dalecurtis** [comment]
I think we still want the X variants since we aren't reducing 4 bytes to 3 bytes during readInto.

**Comment by chcunningham** [comment]
Ah, good point. 

I don't have a strong intuition about whether sites could implement impact optimizations for RGBX (ignoring the alpha plane). If not, I'd vote to just simplify to RGBA.

**Comment by dalecurtis** [comment]
If we go with RGBA, BGRA only we need the hasAlpha flag.

**Comment by chcunningham** [comment]
Triage note: marking 'extension' as the proposals are primarily about adding attributes for keeping/discarding/having alpha.

**Comment by chcunningham** [comment]
Editors call: 
* Marking need-definition to highlight that we should iron this out w/ priority before launch.
* General proposal sounds good.
* For videoFrame.hasAlpha - sounds good, analogous to ffmpeg. For planar formats, hopefully we can just always define the alpha plane as full resolution as the last plane. Will look more at ffmpeg etc.
