### ISSUE TITLE
Unit of the `stride` attribute

### ISSUE THREAD

**Issue by padenot** [w3c/webcodecs#224]
While scrolling twitter randomly, I came across this: https://twitter.com/ID_AA_Carmack/status/1389623925286621184, copied here for posterity:

> "Stride" and "pitch" are often used interchangeably in graphics, but sometimes have bytes vs pixels implied. Pitch has another meaning for displays, so I try to favor stride, and include the units in names to remove ambiguity: byteStride / pixelStride. 
> -- John Carmack

This is made worse by the fact that the pixel formats are not defined.

**Comment by sandersdan** [comment]
Is this for `planes` or for the `readInto()` layout? Assuming we remove `planes`, layouts exclusively describe the output buffer (an `offset` and `stride` for each plane), so I think the intuition will be for the bytes interpretation and the documentation won't need to be extensive. I'm not sure that a longer name is warranted there.

We should define our pixel formats though, at least a table saying the name, number of planes, ordering of bytes in memory, and subsampling resolution. There may be other requirements, like subsample-aligned sizes/regions, but I think they will apply the same to all formats.

**Comment by padenot** [comment]
I'd tend to agree with your assessment (first paragraph), and indeed my issue was opened in the current of the text as it is. It will be better to have a look it's finalized, but I agree that when an API is dealing with `ArrayBuffer`s, bytes become the natural uncontroversial unit. When it's about `stride`, `row` and `length`, it's easy to get confused.

**Comment by chcunningham** [comment]
Triage note: marking 'breaking', as a name change is obviously breaking. But, as pointed out above, it seems likely we'll pursue an alternative change.

**Comment by chcunningham** [comment]
@padenot, with  Planes now removed (#208) are you ok to close this issue?

**Comment by padenot** [comment]
Yep.
