### ISSUE TITLE
Converting AudioSampleFormats for rendering

### ISSUE THREAD

**Issue by chcunningham** [w3c/webcodecs#232]
Following discussion in https://github.com/w3c/webcodecs/issues/179#issuecomment-828856379 we resolved to expose more audio sample formats. This has the benefit of potentially using less memory (vs always float32) and does less throw away conversion. 

But, for decoding -> rendering scenarios, this will sometimes mean that apps need to take an additional step to convert, as WebAudio's AudioWorklet still only supports float32 planar. 

I propose we offer helper method. Something like
`AudioData.getAsPlanarFloat32() -> returns an ArrayBuffer`

@padenot WDYT?

**Comment by padenot** [comment]
https://github.com/w3c/webcodecs/pull/228#pullrequestreview-655540774 is related, and I generally fully agree with your assessment.

**Comment by dalecurtis** [comment]
Isn't this the same as providing the AudioBuffer accessor still? :)

**Comment by chcunningham** [comment]
> Isn't this the same as providing the AudioBuffer accessor still? :)

Yes, but sadly AudioBuffer is mutable and a major goal of this redesign from AudioFrame has been to resolve that wart.

> AudioData.getAsPlanarFloat32() -> returns an ArrayBuffer

One issue with this is the "returns an ArrayBuffer". In the SharedArrayBuffer -> AudioWorklet case, this would mean they need to make another copy to the SAB. We might instead consider something like the VideoFrame API where they provide the buffer and we give them a helper to know what the byte length needs to be.

**Comment by dalecurtis** [comment]
> Yes, but sadly AudioBuffer is mutable and a major goal of this redesign from AudioFrame has been to resolve that wart.

I meant as in something like copyToAudioBuffer(), but to your next point, copyTo() or convertTo() seem superior in eliding copies.

**Comment by chcunningham** [comment]
Triage note: marking 'extension', as proposals above are simply additions to the current interface.

**Comment by chcunningham** [comment]
Plan discussed in https://github.com/w3c/webcodecs/pull/228#issuecomment-837139591 is to extend AudioDataCopyToOptions with an AudioSampleFormat that lets the copy operation simultaneously convert.

**Comment by tguilbert-google** [comment]
I've updated the name to reflect that this is no longer about just a conversion to FLTP, but any format to any format.
