### ISSUE TITLE
Check rfc2119 keyword usage

### ISSUE THREAD

**Issue by padenot** [w3c/webcodecs#249]
There is some limited static analysis we have for free because we use bikeshed, granted we write them in caps (or maybe we need to do it like this `<em class=rfc2129>SHOULD</em>` ? Not sure if this is the respec style, or both).

**Comment by chcunningham** [comment]
@tidoust do you know the latest on this style question?

**Comment by aboba** [comment]
@Djuffin @padenot  Do we still have outstanding RFC 2119 issues?  If not, can we close this?

**Comment by padenot** [comment]
afaict we can close this and open new issues if problems arise.
