### ISSUE TITLE
Clarifying codec string semantics

### ISSUE THREAD

**Issue by chcunningham** [w3c/webcodecs#253]
A origin trial participant noted that the videoEncoder produces constrained baseline AVC when they requested AVC. They indicated that they are happy with that behavior but asked for clarification about which parts of the codec string indicate firm requirements vs those that may be hints or satisfied with a feature subset.

We went back and forth on this [in the chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=1204295), but the best like proposal (and one that matched user expectations) was: 
  - Profile: must exactly match request
  - Constraint Bits: at least as constrained as request
  - Level: level not greater than request

I would like to propose amended guidance for Level: not greater than requested, unless some other parameter explicitly indicates. For example, if the config provides a bitrate or height/width that is outside the bounds of the level, give that precedence. I expect this is what users would prefer. An alternative like "throw an error if config.bitrate is outside bounds of config.codec's level" seems way too fussy.

**Comment by chcunningham** [comment]
@padenot @aboba @sandersdan,  if this seems reasonable I'll update the codec string portion of the spec w/ some clarifications from above.

**Comment by dalecurtis** [comment]
Editor's call: sound good to @padenot, @aboba still looking.
