### ISSUE TITLE
Integrate AbortSignal with the WebCodecs API.

### ISSUE THREAD

**Issue by dalecurtis** [w3c/webcodecs#254]
Since decoding is expensive and processing is always in-sequence it makes sense to offer users a way to abort pending operations. The normative way for doing this is with an [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal).

At least for ImageDecoder there's only place it makes sense: ImageDecodeOptions would add an AbortSignal parameter.

For the audio, video encoders and decoders it's a bit more complicated. I think adding it to encode(), decode(), configure(), and flush() seems like the full list of things we'd want.

**Comment by sandersdan** [comment]
For comparison, `Streams` used `AbortSignal` in `StreamPipeOptions`, which is used for `pipeThrough`, `pipeTo`, where it can be used to cause cancellation of the source (and configurable abortion of the destination).

By my understanding, this is exactly the same as `VideoDecoder.reset()`. Are you proposing this as an alternative or replacement syntax for `reset()`?

For `ImageDecoder`, there is already an ability to use this functionality when using the `Streams` interface for providing data, in addition to the `reset()` method.

**Comment by dalecurtis** [comment]
This would be used to allow finer grained per-operation aborts versus having to reset/close the entire decoder.

**Comment by sandersdan** [comment]
I oppose this on the grounds that without a completion feedback mechanism the implementation of abort is ill-defined, and the whole thing is extremely complicated (even more so that the `Promise`-based API that we had for a while). I would prefer to encourage applications to queue less work, and for implementations to optimize `reset()` in cases where it is followed immediately by a compatible `configure()`.

**Comment by chcunningham** [comment]
Agree with @sandersdan. 

As I read the comments from Sqoosh folks, they don't seem especially concerned with fine-grain control (e.g. abort the current decode but not the upcoming decode already in the control message queue). Seems they just want a way to abort potentially expensive work. The various reset() algos intend to allow both clearing the message queue _and_ aborting the current operation.

**Comment by dalecurtis** [comment]
Can you elaborate on abort() being ill-defined? It's certainly ill-defined right now since I just opened the issue for discussion :) Or do you mean by it's nature we won't ever be able to properly define it? I can kind of see that for the video/audio encoder/decoder APIs since they aren't promise based.

I admittedly had only thought through the ImageDecoder case at the time of posting. In that case, it seems fairly easy to specify 'Aborts the promise returned by decode() and attempts to cancel the work started for it.'

**Comment by sandersdan** [comment]
> Can you elaborate on abort() being ill-defined?

It's hard to define in general since it's not clear what to do with later requests when an earlier one is aborted. Where it becomes ill-defined is when an abort request occurs concurrently with request processing (which is always the way the spec is currently written). We can't say with certainty whether any particular request is abortable.

> I admittedly had only thought through the ImageDecoder case at the time of posting

It does make more sense for `ImageDecoder` where individual requests are mostly orthogonal to state changes in the codec.

**Comment by surma** [comment]
I can only speak for `ImageDecoder` and I think some form of abort would be very useful (and as @sandersdan say, each decode is self-contained and therefore abortable without side-effects). `AbortController` is the platforms primitive and it would be nice to use it.

That things get more complicated in the context of audio and video streams, I can understand. I can’t justify a strong opinion here with my extremely superificial knowledge, but I’d say WHATWG streams set the precedent here and if possible, Web Codecs should strive to mirror the semantics.

**Comment by chcunningham** [comment]
@surma, is `imageDecoder.reset()` sufficient for your use case?

**Comment by surma** [comment]
Just took a look at the spec: Yeah, seems like it does what is needed. There is still some value in supporting the platform’s default orchestration pattern, but I’ll leave that up to y’all.

**Comment by Djuffin** [comment]
Aborting individual decodes seems very tricky in case of video decoder. 
Let's say we abort decoding of a key frame, should this silently abort decoding of all future frames depending on it? 

Aborting a configure() might cause all future decode requests to be aborted, but not always.

I don't think it's possible to spec any kind of consistent behavior here.

**Comment by dalecurtis** [comment]
I'm convinced by the issues around (Audio|Video)(Decoder|Encoder), so it seems if we added this it would only be useful for ImageDecoder and it's unclear if there's a real need for per-decode() aborts that isn't satisfied by reset().

**Comment by chcunningham** [comment]
Per above, I vote to close. If no objection, I'll close sometime next week.

**Comment by dalecurtis** [comment]
sgtm. I wasn't sure if we wanted to close or tag as 'probably-not' -- either is fine with me.
