### ISSUE TITLE
How to encode aac-lc in webcodecs

### ISSUE THREAD

**Issue by runner365** [w3c/webcodecs#259]
Hi, I try to encode aac-lc in webcodecs:
try in the way:
```
this.aencoder_.configure({ codec: 'aac', numberOfChannels: 2, sampleRate: 44100 });
```
try in the way:
```
this.aencoder_.configure({ codec: 'mp4a.40.02', numberOfChannels: 2, sampleRate: 44100 });
```
try in the way:
```
this.aencoder_.configure({ codec: 'mp4a.40.2', numberOfChannels: 2, sampleRate: 44100 });
```
try in the way:
```
this.aencoder_.configure({ codec: 'mp4a.40.17', numberOfChannels: 2, sampleRate: 44100 });
```
but They turns out: "unsupported codec type".

I read reference from: 
* https://www.w3.org/TR/webcodecs-codec-registry/#audio-codec-registry
* https://developer.mozilla.org/en-US/docs/Web/Media/Formats/codecs_parameter
* http://mp4ra.org/#/object_types

But I fail to get the answers, Please help.

**Comment by chcunningham** [comment]
I think your the mp4a* strings are all correct, but you're getting "unsupported" simply because we (Chrome) haven't implemented aac encoding yet. Currently the only supported audio encoder is opus. AAC encode support is on our roadmap, but it may not be included at initial launch.

**Comment by sandersdan** [comment]
AAC encoding in Chrome's WebCodecs implementation is experimental, and in particular is available on Windows behind the flag `--enable-features=PlatformAudioEncoder`

You can track the progress of that implementation at https://bugs.chromium.org/p/chromium/issues/detail?id=1259883 and are welcome to begin testing!

**Comment by rafael2k** [comment]
Any way to get a chrome version with AAC support?

**Comment by dalecurtis** [comment]
Stable macOS and Windows versions support AAC encoding. Please file bugs at https://crbug.com/new if you run into any issues.

**Comment by tlecoz** [comment]
Hello Dale Curtis,

It s not a bug but as far as i know there is no working exemple of an
audio/video transcoding that output a mp4 file.

It could be very helpful if you could provide one.

Le jeu. 12 janv. 2023 à 18:49, Dale Curtis ***@***.***> a
écrit :

**Comment by rafael2k** [comment]
I just would like help with a sample to create an AAC in ADTS format, audio only.

**Comment by dalecurtis** [comment]
You should just be able to configure the encoder for aac and attach ADTS headers to the output samples. Is that not working?

mp4box.js should support aac muxing, but I haven't tried it.

**Comment by rafael2k** [comment]
I don't need / want mp4box.js. WebCodecs standard already provides AAC in ADTS format.

**Comment by rafael2k** [comment]
I think I should use something like this right:

```
        const config = {
          numberOfChannels: music_buffer.numberOfChannels,
          sampleRate: sampleRate,
          codec: "mp4a.40.2",
          aac: { format: 'adts' },
          bitrate: 128000
        };
```

**Comment by dalecurtis** [comment]
Ah, we forgot to implement https://www.w3.org/TR/webcodecs-aac-codec-registration/#aac-encoder-config -- filed https://bugs.chromium.org/p/chromium/issues/detail?id=1407013

You can pretty simply append an adts header in javascript using the current implementation though.

**Comment by rafael2k** [comment]
Thanks Dale! Have a nice day!

**Comment by rafael2k** [comment]
One more question: you mentioned mp4box.js, which is great, but do you also know about some javacript muxer for webm/matroska format? I saw one in this repo in the examples folder, but it seems a video-only muxer. I think I'll use Opus for now, as its implementation in WebCodecs seems a bit more mature and works on Linux / MacOS / Windows and Android already. But I also could find no sample which encodes to Opus and mux to webm.

**Comment by dalecurtis** [comment]
Unfortunately I'm not aware of a webm/mkv muxer of similar quality to mp4box.js. Folks have just found a few random ones lurking around GitHub. It shouldn't be too hard to add audio to a video only muxer. It's should only be adding the audio related EBML fields.

**Comment by rafael2k** [comment]
Yay already committed, tks Dale!
https://chromium.googlesource.com/chromium/src/+/5bb89226f7e788fef09f0154c853cb136c008dc1
Which version will have it already? Nightly already picks it?

Cheers!

**Comment by rafael2k** [comment]
I think it would be nice to have a sample here with a simple audio encoding software to AAC/ADTS and let the audio be downloaded.

**Comment by Djuffin** [comment]
AAC/ADTS switch in Chromium is still work in progress. I'll put a link to a sample here when it's done.

**Comment by rafael2k** [comment]
Thanks Eugene! I wanted to say that it would be nice to have some sample code for an audio encoding pipeline for AAC in ADTS format here: https://github.com/w3c/webcodecs/tree/main/samples

**Comment by dalecurtis** [comment]
Looks like 112.0.5600.0 per
https://storage.googleapis.com/chromium-find-releases-static/5ef.html#5ef816ccd77177d316eb89317ee060fc211fbb59

**Comment by Djuffin** [comment]
Currently, Chromium only supports AAC encoding on Windows and MacOS

**Comment by rafael2k** [comment]
Right. Do you think there is a chance in the future it also supports it in Android, as the Fraunhofer AAC implementation is there?

**Comment by rafael2k** [comment]
ffaac (ffmpeg aac implementation) is also complete and can support all mpeg 4 aac profiles listed in the standard, so Linux could also benefit from this.

**Comment by jiyeyuran** [comment]
good news, chrome(120) is about to support AAC on Android.

**Comment by rafael2k** [comment]
Yay! Support on Windows, Mac and Android. Only Linux missing now!
: )

**Comment by tlecoz** [comment]
Great news ! Thanks for sharing !
