### ISSUE TITLE
Knob for VBR vs CBR encoding

### ISSUE THREAD

**Issue by chcunningham** [w3c/webcodecs#265]
The API currently offers 'bitrate', but no mention of VBR vs CBR. As proposed in https://github.com/w3c/webcodecs/issues/241#issuecomment-845743427, the default should be VBR (principle: don't constrain features/quality unless the user asks for it), but many users will want CBR, so lets give that option.

Strawman to get the discussion going: what if we just copy (or even normatively reference) the enum from MediaRecorder?
https://www.w3.org/TR/mediastream-recording/#bitratemode

```
enum BitrateMode {
  "constant",
  "variable"
};
```

We could then extend the `VideoEncoderConfig` with a new `BitrateMode bitrateMode` member alongside the existing `bitrate`.

**Comment by padenot** [comment]
That looks like a good way forward.

**Comment by aboba** [comment]
@padenot Agreed.
