### ISSUE TITLE
Rewrite mention of clock domain in explainer. The term carries unnecessary connotations.

### ISSUE THREAD

**Issue by dalecurtis** [w3c/webcodecs#273]
The explainer says:

> Clocking: the ability to drive the decoding or encoding using a specific clock domain, to be able to control clock drifts

What it really means is WebCodecs allows clients explicit rendering control. I.e., they can align their audio/video however they want instead of relying on the user agent to do so for them. E.g., beyond what HTMLMediaElement.playbackRate allows today. 

Technically this is already possible with WASM + Canvas + AudioWorklet, so I'm not sure there's a reason to mention it at all.

**Comment by sandersdan** [comment]
I think that when it was originally written, at least some participants expected reclocking to be in-scope for WebCodecs. The API as it stands today however is firmly lower-level than that.

**Comment by dalecurtis** [comment]
Thanks for more context. I think that supports removal then.

**Comment by dmcardle** [comment]
Thanks, Dale. My original concern was that this API might expose a way to estimate clock skew with high precision. Is it correct to say that the `Encoded{Audio,Video}Chunk.timestamp` fields have nothing to do with hardware clocks, and that they are strictly functions of the media being decoded/encoded?

**Comment by sandersdan** [comment]
That's correct.

Note that the separate [MediaStreamTrackProcessor](https://w3c.github.io/mediacapture-transform/#track-processor) API does produce WebCodecs `VideoFrames` with timestamps related to capture. These are the same or even more restricted than what the WebRTC protocol already caries, but depending on the UA implementation they could be provided by the OS and in turn from a hardware source at up to microsecond precision.

**Comment by dmcardle** [comment]
Thanks for clarifying!

**Comment by padenot** [comment]
As Dan said, this was when we first started drafting the API, sometime in summer 2019. At the time, the API input and output were WhatWG Streams and MediaStreams, and so there was a need for some clocking facilities.

These days, not only WhatWG streams aren't used, but MediaStream integration has moved elsewhere.

Maybe we should archive this explainer. The spec as it is today is in good shape and the interfaces are clear enough.

**Comment by chcunningham** [comment]
Fixed!

> Maybe we should archive this explainer. The spec as it is today is in good shape and the interfaces are clear enough.

IMO we're getting close, but not quite there yet. We'll want to update the spec with some the explainer's examples (or better examples) and maybe include some of the explainers details on goals / non goals etc.
