### ISSUE TITLE
Moving from V1: this is a maybe-nice-to-have config addition. Adding it later is not a breaking change.

### ISSUE THREAD

**Issue by Frenk8** [w3c/webcodecs#279]
Moving from V1: this is a maybe-nice-to-have config addition. Adding it later is not a breaking change.

_Originally posted by @chcunningham in https://github.com/w3c/webcodecs/issues/103#issuecomment-823777375_

**Comment by chcunningham** [comment]
This seems to have been opened by mistake? LMK if this was intended to track a new request.
