### ISSUE TITLE
More types should be Serializable

### ISSUE THREAD

**Issue by sandersdan** [w3c/webcodecs#289]
In addition to `VideoFrame` and `AudioData`, other interface types should be serializable:

- `EncodedAudioChunk`
- `EncodedVideoChunk`
- `VideoColorSpace` (not yet in the spec)

It may make sense to add `close()` and add transfer to `EncodedAudioChunk` and `EncodedVideoChunk`, but they are immutable by design and therefore do not need transfer to avoid copying.

**Comment by padenot** [comment]
This will be quite useful, yes.
