### ISSUE TITLE
Add privacy considerations section

### ISSUE THREAD

**Issue by steveanton** [w3c/webcodecs#29]
At TPAC it was brought up that there are some privacy concerns with low-level codec access. We should try to address some of these concerns in the explainer.

A couple concerns that were brought up:
- Precise timing information of encode/decode and codec limitations could be a fingerprinting surface.
- Codec capabilities are a fingerprinting surface.

**Comment by padenot** [comment]
The privacy review request, for reference: https://github.com/w3cping/privacy-request/issues/38.

**Comment by chcunningham** [comment]
Now done
https://w3c.github.io/webcodecs/#privacy-considerations
