### ISSUE TITLE
Should we make scalabilityMode change on the fly for VideoEncoder?

### ISSUE THREAD

**Issue by HuaChunbo** [w3c/webcodecs#290]
For example in temporal SVC encoding of WebCodecs, it would be good to have scalabilityMode be able to change on the fly during encoding process. Like to change from L1T2 to L1T3 dynamically, so that we can provide the scalability with more flexibility.

**Comment by aboba** [comment]
The specification allows `configure()` to be called again with the updated `scalabilityMode` value.

**Comment by chcunningham** [comment]
I think this is answered. LMK if more to discuss.
