### ISSUE TITLE
Detached behavior of allocationSize()

### ISSUE THREAD

**Issue by sandersdan** [w3c/webcodecs#294]
Currently `allocationSize()` is specified to return `0` when detached. `copyTo()` however throws `InvalidStateError`.

It seems to me that throwing from `allocationSize()` would be overall safer and more consistent.

**Comment by tguilbert-google** [comment]
Parallel question: `allocationSize()` with `AudioDataCopyToOptions.frameCount == 0` doesn't throw. There isn't anything wrong with copying `0` frames, but should it throw instead?

**Comment by chcunningham** [comment]
Will send a PR for this soon.

**Comment by sandersdan** [comment]
> There isn't anything wrong with copying 0 frames, but should it throw instead?

I don't have a good answer for this. For `VideoFrame`, this behavior falls out of defining frame rects to have nonzero area. You can't create a frame with a zero-area `visibleRect` or copy a zero-are `rect` of a frame.

The same approach doesn't apply since `AudioData` has a primitive type to describe extent, but the philosophy can be copied. Currently the constructor does allow zero-length frames, so `copyTo()` should also allow that.

If it's problematic to have zero-sized `AudioData`, it should first be banned in the constructor, then it might make sense to also ban it in `copyTo()`.

If you think that should be done, please open a separate issue for it.
