### ISSUE TITLE
scalability mode registry?

### ISSUE THREAD

**Issue by aboba** [w3c/webcodecs#295]
Since we're taking the registry approach for configuration in general, would it make sense to create a registry for scalability modes and associated diagrams? 

Related issue: https://github.com/w3c/webrtc-svc/issues/47

**Comment by chcunningham** [comment]
Editors Call: no objection to using a registry. Seems workable.

**Comment by chcunningham** [comment]
@aboba anything left to track for us (vs webrtc-svc) here?

**Comment by chcunningham** [comment]
EC: good to close - track in w3c/webrtc-svc#47
