### ISSUE TITLE
Should AudioData offer format conversion?

### ISSUE THREAD

**Issue by tguilbert-google** [w3c/webcodecs#296]
Decoders can emit `AudioData` with the `FLT` format. This forces users to manually de-interlace into the `FLTP` format needed for WebAudio.

User Agents can make use of native SIMD instructions, with less overhead than setting up WASM. It would be overall simpler for User Agents to offer this conversion than for users to write or import conversion code.

A proposal would be to add a `format` parameter to be used by `allocationSize()` and `copyTo()`, in the following way:

```
AudioDataCopyToOptions {
  // ...
  AudioSampleFormat format;
}
```

**Comment by sandersdan** [comment]
Is it straightforward to convert between all of the formats, or is this intended just for planar/interleaved conversions with the same underlying type?

For `VideoFrame`, a simple conversion might be RGBA -> BGRA, while RGBA -> I420 is more involved and has performance/quality tradeoffs.

**Comment by tguilbert-google** [comment]
The idea would be conversion from any type to any other. This is covered in #232, but the name needs an update to reflect converting to formats other than float32 planar.
