### ISSUE TITLE
echidna publish failing

### ISSUE THREAD

**Issue by chcunningham** [w3c/webcodecs#298]
A recent merge failed to publish
https://github.com/w3c/webcodecs/actions/runs/1016764190

I guess our patent policy links need an update. Not sure how to trigger that. @tidoust can you give me pointers?

**Comment by chcunningham** [comment]
@tidoust, friendly ping

**Comment by chcunningham** [comment]
@tidoust, checking in.

**Comment by tidoust** [comment]
Oops, sorry, I missed that issue somehow and then was out of office.
Yes, links need fixing in Bikeshed. I'll take care of that.

**Comment by tidoust** [comment]
I filed https://github.com/tabatkins/bikeshed/pull/2124 to have the boilerplate text reference the latest version of the Patent Policy. Once merged, a new version of Bikeshed will need to be released for our deploy scripts to get the updated text.

#328 should take care of the image that the spec now embeds.

**Comment by tidoust** [comment]
Publication is back to green and /TR documents are now up-to-date with the repo. Closing this issue accordingly. Sorry again that I failed to notice the issue right away despite the ping!
