### ISSUE TITLE
Per-Frame control versus average bitrate targets

### ISSUE THREAD

**Issue by aboba** [w3c/webcodecs#308]
A 2018 [USENIX paper](https://www.usenix.org/conference/nsdi18/presentation/fouladi) argues for closer coupling of the encoder to the transport by allowing the encoder to offer multiple frame sizes, with the transport choosing between them.  This produces lower latency. 

Slides are [here](https://irtf.org/anrp/IETF111-ANRP-Fouladi.pdf).
Video is [here](https://irtf.org/anrp/).

**Comment by padenot** [comment]
The complexity with this is the encoder state snapshotting mechanism. It's going to be hard to reconcile the design in this paper and a generic media encoding and decoding API, but it's probably worth it.

iirc from reading it back in the days the results are quite impressive.

**Comment by aboba** [comment]
@padenot Agree that the approach suggested in the paper may be a "bridge too far".  But it might be possible to achieve similar objectives by other means (e.g. using spatial scalability, control of reference frames, etc.).

**Comment by aboba** [comment]
I believe this is covered by the work on per-frame QP as well as by spatial scalability support.
