### ISSUE TITLE
Use of EncodingError

### ISSUE THREAD

**Issue by sandersdan** [w3c/webcodecs#309]
The spec requires an `EncodingError` to be thrown in the case of a decode error. I have two minor concerns with this:

- It's not always clear whether a decoding error is actually caused by a bitstream issue.
- `EncodingError` seems to have been originally intended to indicate issues with text encodings.
  - Our use isn't unprecedented, though, WebAudio also throws `EncodingError`.

I suggest `OperationError` as a more general choice.

**Comment by chcunningham** [comment]
WebIDL spec gives the description

"The encoding operation (either encoded or decoding) failed."
https://heycam.github.io/webidl/#encodingerror

So I think it's fair for us to use it in WC. That description isn't specific about bitstream vs internal errors, so I think either usage works. I'm open to creating a different error for bitstream vs internal, but it's my understanding that we (the UA) can't always distinguish given limited info from the underlying codec.

**Comment by chcunningham** [comment]
Lets settle this ASAP. Its a potentially breaking bikeshed.

**Comment by sandersdan** [comment]
SGTM, that definition does seem broad enough to cover our use, and it's unlikely anyone will be confused.

There are some places in the spec that it would make sense to allow `OperationError` where currently there is no error path (eg. during a `copyTo()`), but that can be handled separately / as a v2 extension.
