### ISSUE TITLE
Random acces in video

### ISSUE THREAD

**Issue by BrentZ-1849203** [w3c/webcodecs#314]
Let's assume I want to decode the 30th chunk and only that chunk. Currently, I converted my video to only include I-frames which allows me to achieve this by skipping decode() on all chunks up until 30 and then decoding the 30th chunk. If I did not convert the video to only include I-frames, skipping decodes resulted in not getting the required chunk.

Is there a more efficient way to achieve random access without converting to I-frames?

**Comment by dalecurtis** [comment]
Yes, you'll want to ensure you have a keyframe index. Then you can decode all the frames starting from the most recent keyframe before the target frame and drop them until you reach your desired frame.

(Since this is more a request for help than a WebCodecs issue, I'll close this)
