### ISSUE TITLE
Are `AudioDecoderConfig.{sampleRate,channelCount}` always required, sometimes ignored, moved to the registry ?

### ISSUE THREAD

**Issue by padenot** [w3c/webcodecs#317]
Some audio codec will need them, some won't use them.

For WAV, it's just a stream of numbers after having parsed the RIFF header. Web Codecs will only deal with the numbers (it's going to be either a `memcpy` or a trivial inflation from 24bits to 32bits really), and those numbers are meaningless without having a sample-rate and channel count, so it's kind of required.

But it's useless for the others, where those numbers are not in the container, just in the codec byte stream, and we don't want to have authors parse the header of the codec to get the correct values, because that would break the container/codec abstraction. 

It's annoying to have something optional in the IDL but required for a particular codec.

**Comment by dalecurtis** [comment]
EC: Lets keep it required, codec registry entries with optional fields can state that it's ignored.
