### ISSUE TITLE
OpusBitstreamFormat for AudioEncoderConfig

### ISSUE THREAD

**Issue by chcunningham** [w3c/webcodecs#342]
Opus follows the pattern of AVC and AAC in having at least two ways to packetize the encoded chunk data. Currently the registration defines how the AudioDecoderConfig.description to signals the packet type, but we should add something like OpusBitstreamFormat { "opus", "ogg" } (check me on the names) for the AudioEncoderConfig to signal a desired encoded output format.

**Comment by padenot** [comment]
Firefox currently only supports the Opus bitstream format. We could add OGG containerization, but we could also remove this from the standard if nobody has even implemented it, and nobody feels the need for it.
