### ISSUE TITLE
Odd-sized visibleRects

### ISSUE THREAD

**Issue by sandersdan** [w3c/webcodecs#348]
In PR https://github.com/w3c/webcodecs/pull/347, the question of odd-sized `visibleRect`s for 4:2:0 (and subsampled content in general) content has come up. I am unsure whether the potential solutions would be onerous for some WebCodecs implementations.

Some background:
- 4:2:0 subsampled content has U/V planes with half the horizontal and vertical resolution of the Y plane. If the Y plane has odd size, then the U/V planes have fractional size. Fractional planes are not well-defined.
- H.264 cannot store an odd `visibleRect`, but [libvpx can](https://groups.google.com/a/webmproject.org/g/webm-discuss/c/LaCKpqiDTXM/m/ufryPKc1AuUJ). Note that unlike for H.264, libvpx `visibleRect` always has `top`/`left` = 0.
- It is not possible to copy an odd-sized 4:2:0 rect, so we must copy either more or less area than requested.
- YUV conversion also operates on full samples, so we must convert either more or less area than requested.

Some specific problems to consider:
- `VideoFrame.copyTo()` copies the frame's `visibleRect` by default.
- Encoding a 4:2:0 frame that has a `visibleRect` with an odd `top`/`left` to VPx requires resampling the picture because we cannot shift the U/V planes by a fractional amount just with pointer arithmetic.
- Capture from `<canvas>` can easily be odd-sized 4:4:4, and it will usually be immediately converted to 4:2:0 YUV.
- Since libvpx can decode 4:2:0 frames with odd `visibleRect`, we will be forced to pick an approach eventually.

Some strategies we could consider:
- We could reject odd `visibleRect`s for 4:2:0 content in all cases, including VPx.
- We could round odd `visibleRect`s inwards when necessary. This may be more convenient for apps than outright rejecting and remains simple to implement. It would be best if we could precisely define "when necessary" so apps can rely on the exact behavior (eg. accurately predict the dimensions that `copyTo()` will use).
- We could round outwards instead. This may introduce line-like artifacts at the edges.
- We could copy the strategy libvpx uses, which is to leave the Y plane alone but round the U/V plane size up. All processing code needs to be aware that it is safe to sample outside of the `visibleRect` for U/V but not for Y. We will still need to either reject or resample when the `visibleRect` `top`/`left` is odd. Note that under this definition it is possible for a 4:2:0 Y plane to have odd coded size, so the U/V planes may be "bigger".

After reviewing the options, my personal preference is to round inward where necessary, and define the necessary places as everywhere for `visibleRect` `top`/`left`, but preserve odd `width`/`height` for YUV conversions and VPx/AV1 encode/decode. (Other codecs and `copyTo()` would round `width`/`height` inward.) If we went this way, I would also propose adding resolution information to the `copyTo()` output metadata.

**Comment by ccameron-chromium** [comment]
I've been encountering 135p as a common format (1080p downsampled 2x, 3 times). It has hit a handful of bugs on macOS, but so far all of them have been bugs in Chrome's code (macOS is supporting things just fine). In that work, I did briefly add support for odd-width buffers, and that caused lots of problems (IIUC it was libyuv rejecting things, but that may be a lie).

All of the libraries that I've used in that work used the convention that the UV size was rounded up. I managed to side-step trying to figure out what to do with the visibleRect.

I'm not sure what the best scheme is here.

**Comment by sandersdan** [comment]
I believe I've come to a tolerable set of tradeoffs. The proposal favors rejecting (throwing exceptions) over any automatic behavior, allowing some room for future additions.

Here I use "odd" to mean "not a multiple of the subsampling factor".

# Proposal

## Offsets

Odd offsets are rejected in all APIs. **Rationale:** allow implementations to handle `visibleRect` using only pointer arithmetic, no resampling.

## Sizes
### VideoFrame Construction

Allow odd sizes. The coded size must be even so the result is well-defined. Implementations must support rendering odd sizes (eg. in `drawImage()`).

**Risks:** It's possible that odd-sized rendering could be difficult for some implementations (eg. rendering via subsampled hardware overlay), but I am not aware of any specific cases.

### copyTo()

Reject odd sizes, including when inferred as a default value.

**Risks:** This is a footgun since the default behavior will not be guaranteed to be reliable. The exception message can be quite clear, at least. Every alternative considered is also surprising in some way.

## Encoding

`VideoEncoderConfig` is limited only by the codec selected. For example, H.264 codecs will reject odd sizes but AV1 codecs will not.

Taking H.264 4:2:0 as an example, an odd size will be rejected at configuration time, so the configured size must be even. Therefore calling `encode()` with an odd-sized frame will always trigger scaling.

### YUV conversion

The underlying coded sizes are always even, so YUV conversion is always well-defined.

**Comment by chcunningham** [comment]
Thanks @sandersdan, this all sounds good to me. One point to clarify: IIUC the above proposals about when odd sizing is restricted are limited to pixel formats that use subsampling (e.g. I420). For formats that don't subsample (e.g. I444), am I right that odd sizing would be allowed in all scenarios you mentioned?

**Comment by sandersdan** [comment]
That is correct.

**Comment by chcunningham** [comment]
Fixed by #402
