### ISSUE TITLE
[SecureContext]

### ISSUE THREAD

**Issue by padenot** [w3c/webcodecs#350]
Is there any reason to allow this on insecure origins?

**Comment by aboba** [comment]
It should be secure context.

**Comment by chcunningham** [comment]
Editors call:
- What is Chrome's position on new features generally?
- Some integration points already SecureContext. Yes: getUserMedia(), WebGPU. No: WebAudio, <video>
- Concerns: encouraging https, reducing fingerprinting ability http injection
