### ISSUE TITLE
MP4 segment decode support？

### ISSUE THREAD

**Issue by ringcrl** [w3c/webcodecs#358]
I noticed the example of decoding using MP4 Box, but the common reality is that I only need to decode some of the MP4 clips, and it would be a huge loss and inefficiency to download the full MP4 file every time, so I was wondering if there is any solution to support MP4 clip decoding

**Comment by sandersdan** [comment]
Demuxing is outside of the scope of WebCodecs, however I will note that `mp4box.js` does support random access. The `appendBuffer()` method returns an offset for the next read, and there is a `seek()` method that uses the same approach.

**Comment by chcunningham** [comment]
More details on the ingredients:
* host a fragmented mp4
* download only the bytes of the mp4 that you need for your clip (roughly: the moov atom followed by whatever moof matches the timeline of interest)
* use mp4box to demux those bytes
* feed demuxed packets into VideoDecoder
