### ISSUE TITLE
Update TR published codec registrations (fix broken registry links)

### ISSUE THREAD

**Issue by chcunningham** [w3c/webcodecs#359]
Several of the links in the https://www.w3.org/TR/webcodecs-codec-registry/ don't work. 

busted: https://www.w3.org/TR/webcodecs-aac-codec-registration/ 
working: https://w3c.github.io/webcodecs/aac_codec_registration.html

@tidoust, can you advise on how to get the codec registrations published to TR? IIRC, something about generating echidna tokens?

**Comment by tidoust** [comment]
To generate Echidna tokens, specs needs to have been published as First Public Working Drafts (FPWD) to /TR.

To publish FPWD of these specs, I need approval from the group.

In other words, that all starts with issuing a call for consensus to publish the list of WebCodecs registration specs as FPWD, noting that these specs are intended to be published as WG Notes. @chrisn, @jernoble?

**Comment by chrisn** [comment]
Yes, we can send out a CfC. I noticed that the [registry](https://w3c.github.io/webcodecs/codec_registry.html) contains a couple of inline issues. Can we resolve these before FPWD?

**Comment by tidoust** [comment]
I note that the registry itself and the AVC (H.264) WebCodecs Registration have already been published as FPWD (and /TR version gets updated whenever a push gets made to the main branch on these specs). The call for consensus would be for the other WebCodecs registrations, namely the ones for FLAC, MP3, AAC, OPUS, VORBIS I, AV1, VP8, and VP9.

**Comment by chcunningham** [comment]
Thanks guys. I've sent #367 and #368 to prepare for FPWD. When those merge we should be good to run Cfc.

**Comment by chcunningham** [comment]
The blocking issues above are now resolved. @chrisn, please go ahead with CFC to publish the new registrations. 

For reference, the new registrations to publish are:
- https://w3c.github.io/webcodecs/aac_codec_registration.html
- https://w3c.github.io/webcodecs/alaw_codec_registration.html
- https://w3c.github.io/webcodecs/av1_codec_registration.html
- https://w3c.github.io/webcodecs/flac_codec_registration.html
- https://w3c.github.io/webcodecs/mp3_codec_registration.html
- https://w3c.github.io/webcodecs/opus_codec_registration.html
- https://w3c.github.io/webcodecs/pcm_codec_registration.html
- https://w3c.github.io/webcodecs/vorbis_codec_registration.html
- https://w3c.github.io/webcodecs/vp8_codec_registration.html
- https://w3c.github.io/webcodecs/vp9_codec_registration.html

These documents should also be republished to reflect the latest updates
- https://w3c.github.io/webcodecs/avc_codec_registration.html
- https://w3c.github.io/webcodecs/codec_registry.html (main registry document)

**Comment by chcunningham** [comment]
@tidoust, the CfC closed (resolving to publish). Please go ahead and publish the above to FPWD. Let me know if I can do anything to help.

**Comment by tidoust** [comment]
Yes, I'm on it. The transition was approved (see https://github.com/w3c/transitions/issues/398). Publication should take place on Thursday. There is a broken reference in some of these specs, which I'll fix in published documents (see PR #423).

FWIW, the exact status for draft notes is not FPWD in Process 2021. These documents will be published on the Note track as Draft Group Notes.

**Comment by tidoust** [comment]
All codec registrations got published to /TR today. Specref picked up the new specs and Bikeshed reference database was updated accordingly. In order to update the codec registry itself and fix the links, a gentle push to the `main` branch needs to happen (because spec-prod considers that it should skip publication to `gh-pages` and /TR if action that triggers it is not a "push" event). You could perhaps merge one of the pending bug fixing PRs (#419 or #423) or just add a space somewhere. Whatever you prefer, we just need a push!

**Comment by padenot** [comment]
Done, thanks.

**Comment by chcunningham** [comment]
Thanks everyone! I confirmed just now that all the links are working :D
