### ISSUE TITLE
WebM - extract chunks

### ISSUE THREAD

**Issue by kareljuricka** [w3c/webcodecs#374]
Hi,

just wanna ask for some tip / guide, how can I get chunks for Webm files.
For mp4 I'm using https://github.com/gpac/mp4box.js/ inspirated by this example (https://github.com/w3c/webcodecs/tree/main/samples/mp4-decode)
But when I wanna do same for webm, I'm not pretty sure how to start.

I found https://github.com/jscodec/jswebm and  https://github.com/Yahweasel/mkvdemuxjs
but both throw error during decoding generated packets:
(index):46 Uncaught (in promise) DOMException: Failed to execute 'decode' on 'VideoDecoder': A key frame is required after configure() or flush().

Thanks for any help

**Comment by sandersdan** [comment]
The key frame message refers to `EncodedVideoChunk.type`. Taking `jswebm` as an example, you would write something like: `new EncodedVideoChunk({ type: packet.isKeyframe ? 'key' : 'delta', data: packet.data, timestamp: packet.timestamp * segment.timecodeScale / 1000)})`. Make sure that you do in fact start decoding at a keyframe.

**Comment by kareljuricka** [comment]
@sandersdan thanks for your reply.
I set type exactly as you written and also checked that first packet is really keyframe - it is.
But problem persists :(

**Comment by sandersdan** [comment]
Can you upload your code and a sample file so that we can try to reproduce?

**Comment by kareljuricka** [comment]
I did more analysis and find out that it's because of wrong codec - vp9. I configured vp8..
with codec: 'vp09.00.10.08' it works..

**Comment by Tenpi** [comment]
Hello, when I extract webm frames all of the frames have a width/height of 0 (so a black screen video file). I am using JsWebm, I suspect it is because of the decoder config, since JsWebm doesn't provide a config I set it manually... am I doing it correctly?

```ts
public static extractWebMFrames = async (videoFile: string, duration: number) => {
        let minFrames = duration * 12
        let frames = [] as any
        await new Promise<void>(async (resolve) => {
            let demuxer = new JsWebm()
            const arrayBuffer = await fetch(videoFile).then((r) => r.arrayBuffer())
            demuxer.queueData(arrayBuffer)
            let timeout: any 
            // @ts-ignore
            let decoder = new VideoDecoder({
                output : (frame: any) => {
                    clearTimeout(timeout)
                    const bitmap = createImageBitmap(frame)
                    frames.push(bitmap)
                    frame.close()
                    timeout = setTimeout(() => {
                        if (frames.length < minFrames) return 
                        resolve()
                    }, 500)
                },
                error : (e: any) => console.error(e)
            })
            while (!demuxer.eof) {
                demuxer.demux()
            }
            decoder.configure({
                codec: "vp09.00.10.08",
                codedWidth: demuxer.videoTrack.width,
                codedHeight: demuxer.videoTrack.height,
                displayAspectWidth: demuxer.videoTrack.width,
                displayAspectHeight: demuxer.videoTrack.height,
                colorSpace: {
                    primaries: "bt709",
                    transfer: "bt709",
                    matrix: "rgb"
                },
                hardwareAcceleration: "no-preference",
                optimizeForLatency: true
            })
            let foundKeyframe = false
            for (let i = 0; i < demuxer.videoPackets.length; i++) {
                const packet = demuxer.videoPackets[i]
                if (packet.isKeyframe) foundKeyframe = true
                if (!foundKeyframe) continue
                // @ts-ignore
                const chunk = new EncodedVideoChunk({type: packet.isKeyframe ? "key" : "delta", data: packet.data, timestamp: packet.timestamp * demuxer.segmentInfo.timecodeScale / 1000})
                decoder.decode(chunk)
            }
        })
        return Promise.all(frames)
  }
```

**Comment by sandersdan** [comment]
It's not supposed to be possible to create a zero-sized frame in WebCodecs, but it is possible that a bug in the implementation could result in that outcome. In particular, the `codedWidth`, `codedHeight`, `displayAspectWidth`, and `displayAspectHeight` are checked for validity and you would get no frames at all if they were zero.

More likely though is that `closed` frames appear to have zero size.

I don't see anything obviously wrong with the code you posted, but I can't attempt to reproduce the issue without the source content as well.

I would recommend filing a bug at [crbug.com](https://bugs.chromium.org/p/chromium/issues/entry) with a full reproduction so that we can investigate.

**Comment by Tenpi** [comment]
I'll bring this up with JsWebm first because it seems like the `isKeyframe` property returns `undefined`, so I can't be sure that its sending the correct data to the `VideoDecoder`. Once I am certain that this bug is with the `VideoDecoder`, I'll file a bug with Chrome. Thanks.

**Comment by Tenpi** [comment]
Hi, I submitted this bug on chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=1320997

I just can't seem to get this to work. It either gives me the keyframe error, or all frames have a width/height of 0. I don't know how to do code blocks in chromium issues, but it is the same code I posted before.
