### ISSUE TITLE
VideoFrame.format is null

### ISSUE THREAD

**Issue by jamespearce2006** [w3c/webcodecs#382]
One of the issues I'm running into with using createImageBitmap is that the ImageBitmap returned may be GPU backed, and have a limited lifetime. On mobile devices, if I cache these frames (because I need to be able to play a GOP in reverse, for example), I can run into the situation where they're no longer valid when I come to play them.

As an alternative, I was going to look at VideoFrame.copyTo() to extract the data. However, I've found that the VideoFrame.format property is null, and attempting to call allocationSize to give me the buffer size I need results in this error:
```
Failed to execute 'allocationSize' on 'VideoFrame': allocationSize() is not yet implemented when format is null
```

I'm a doing something wrong? What's best way of handling this situation?

**Comment by sandersdan** [comment]
Yes, decoded frames are required to be output in presentation order, so I would expect it to work.

**Comment by jamespearce2006** [comment]
Hmm... The only thing I can think of is that createImageBitmap returns a promise. Do I need to wait for the previous promise to resolve before calling createImageBitmap for the next frame?

**Comment by sandersdan** [comment]
I don't expect you should have to wait since the execution is (currently) serialized through a single command buffer in our implementation, but it's certainly worth a try.

**Comment by jamespearce2006** [comment]
It doesn't seem to help.
What I've noticed is that it's the last several frames of the GOP that are black. The amount of black frames seems to vary depending on how powerful the device is - the less powerful, the more black frames - which implies some kind of timing issue.

I'll investigate more and open a Chromium bug if I can create a simple example.

**Comment by chcunningham** [comment]
Thanks for filing the Chromium bug. I'm prioritizing it for this quarter.

Also I've filed #436 to track possible VF copy() API. Closing this one as I think everything is now tracked elsewhere. Feel free to reopen if needed.
