### ISSUE TITLE
Can we drop the secure context (https) requirement?

### ISSUE THREAD

**Issue by bp2008** [w3c/webcodecs#383]
Hello.

I am very excited about WebCodecs, but I notice in Chrome 94/95, the API is only available in a secure context (https).  I cannot imagine why, except to arbitrarily promote usage of TLS.  Media processing capabilities have long been available on the unencrypted web by other means.  WebCodecs just makes it (much) more convenient for the developer, and better-performing for the user.  Why is this restricted to secure contexts?

This is a big problem for my use case, which is [a web interface](https://github.com/bp2008/ui3) for popular video security software that is installed locally on end-user machines.  The web interface is hosted locally too (not from "the cloud") using unencrypted HTTP, hence the problem.

The only way most users will use HTTPS is if we force it, and provide a self-signed certificate.  The user experience is awful and it will teach users to navigate through scary browser warnings without a second thought.

**Comment by FergoTheGreat** [comment]
I would love to know the reason why it was thought necessary to limit this to secure contexts only. I know SSL/TLS certificates are considered trivial/essential and used pretty much by default by all corporations these days. I don't like that being an excuse to just give everything a secure context requirement "just to be safe" instead of because it was strictly necessary.

**Comment by tidoust** [comment]
I note issue #350, which details the rationale used for introducing `[SecureContext]` in the first place.

**Comment by Djuffin** [comment]
Chromium policy about new web APIs available in not secure context hasn't changed.
I believe the same is true for Firefox. 

So I don't think we can drop https requirement for webcodecs.

**Comment by Djuffin** [comment]
cc @youennf

**Comment by Djuffin** [comment]
For Chromium based browsers you can use `chrome://flags/#unsafely-treat-insecure-origin-as-secure` to  treat LAN websites as secure

**Comment by chrisn** [comment]
Discussed in Media WG meeting, 10 October 2023 [minutes](https://www.w3.org/2023/10/10-mediawg-minutes.html#t07)

**Comment by BenMcLean** [comment]
> Discussed in Media WG meeting, 10 October 2023 [minutes](https://www.w3.org/2023/10/10-mediawg-minutes.html#t07)

Hope I'm not being too ignorant here, but it looks like this meeting uses the fact that Chromium made a decision as justification for web standards, which means that Chromium sets web standards now and w3 follows them. Isn't it supposed to work the other way around?

**Comment by wicep** [comment]
Yes
