### ISSUE TITLE
Dependency requirements

### ISSUE THREAD

**Issue by aboba** [w3c/webcodecs#389]
It has been observed that WebCodecs Decode API may throw if there is a gap between encoded chunks, even if the references of the chunk passed to decoder.decode(chunk) have been previously decoded successfully. For example, if the base layer has been successfully decoded, but an intervening chunk at a higher temporal layer was not received, attempts to decode the next base chunk will fail, even though the base layer is not dependent on higher temporal layers. 

It has been suggested that may be related to lack of support for decode target filtering/operating point configuration.  Issues resulting from changing the set of decode targets are discussed [here](https://aomediacodec.github.io/av1-rtp-spec/#a4-active-decode-targets): 

"When an SFM changes the set of forwarded Decode targets or an encoder changes the set of produced Decode targets, some Decode targets may become unavailable for decoding. Whenever the set of active Decode targets changes, the sender MUST signal the new set of active Decode targets to the receiver...."

**Comment by chcunningham** [comment]
@aboba, from #399 it sounds like we probably don't strictly need a spec change for this, but maybe Chrome's impl isn't setting necessary flags under the hood to emit all layers? Could you provide some demo code for us to look closer?
