### ISSUE TITLE
Is there an interface demo here ,  not an instruction document ?

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#392]
i know the document is in `https://w3c.github.io/webcodecs/`,so there is demo about how to use the webcodecs api ,such as how to use `frame.VideoFrame.copyTo` ?

**Comment by chcunningham** [comment]
The samples folder @aboba mentioned is live-hosted here https://w3c.github.io/webcodecs/samples/

**Comment by yangfangfang1204** [comment]
ok ,thanks , i know the sample `https://w3c.github.io/webcodecs/samples/` , Is there any other demo, such as the demo of how to use `copyTo`, i know the document is in https://w3c.github.io/webcodecs/ , i think read a demo is better than read the document ?

**Comment by sandersdan** [comment]
I don't think there is a demo of `copyTo()` yet, there are WPT tests that cover it though: https://github.com/web-platform-tests/wpt/blob/master/webcodecs/videoFrame-copyTo.any.js
