### ISSUE TITLE
Video encoding fails with "Encoding Error" without any additional details

### ISSUE THREAD

**Issue by npapagna** [w3c/webcodecs#393]
I'm trying to encode an `mp4` video from an array of images.
The images in that array are user-provided. They will all have the same resolution, but the resolution/aspect ratio is not constrained in any way.

I found out that if I use this particular resolution (`272x185`) encoding a frame fails with the following error without any additional information about what went wrong:

```
DOMException: Encoding error.
  code: 0
  message: "Encoding error."
  name: "OperationError"

ABORT_ERR: 20,
  code: 0,
  DATA_CLONE_ERR: 25,
  DOMSTRING_SIZE_ERR: 2,
  HIERARCHY_REQUEST_ERR: 3,
  INDEX_SIZE_ERR: 1,
  INUSE_ATTRIBUTE_ERR: 10,
  INVALID_ACCESS_ERR: 15,
  INVALID_CHARACTER_ERR: 5,
  INVALID_MODIFICATION_ERR: 13,
  INVALID_NODE_TYPE_ERR: 24,
  INVALID_STATE_ERR: 11,
  message: "Encoding error.",
  name: "OperationError",
  NAMESPACE_ERR: 14,
  NETWORK_ERR: 19,
  NO_DATA_ALLOWED_ERR: 6,
  NO_MODIFICATION_ALLOWED_ERR: 7,
  NOT_FOUND_ERR: 8,
  NOT_SUPPORTED_ERR: 9,
  QUOTA_EXCEEDED_ERR: 22,
  SECURITY_ERR: 18,
  SYNTAX_ERR: 12,
  TIMEOUT_ERR: 23,
  TYPE_MISMATCH_ERR: 17,
  URL_MISMATCH_ERR: 21,
  VALIDATION_ERR: 16,
  WRONG_DOCUMENT_ERR: 4
```

The error does not have any stack trace, so I could not debug what could be going on with the frame encoding.

I managed to create a repro for this issue. You can try it out [here](https://jsfiddle.net/L2tn57qp/1/).
If you change the resolution parameters of the repro to say `1980x1080` it works fine.

This makes me think there is something wrong with the way `VideoEncoder` is configured, but I'm fairly new to video encoding so I don't know what could be going on.

Any leads to fix this will be greatly appreciated.

**Comment by sandersdan** [comment]
H.264 cannot encode odd-sized pictures when using 4:2:0 subsampling. See #348 for more details.

It does seem to be a Chrome bug that the configuration is not rejected by `isConfigSupported()`. I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1266075.

**Comment by npapagna** [comment]
Thanks a lot @sandersdan for the super quick reply & additional info 🙌
