### ISSUE TITLE
High-profile H.264 not decoding properly

### ISSUE THREAD

**Issue by jamespearce2006** [w3c/webcodecs#395]
My stream is: Profile 100, Level 42.

The decoder accepts the configuration, and doesn't generate any errors when decoding the bit stream. The I frame looks OK, but all subsequent frames are not rendered properly.

Should this work with WebCodecs?

I've attached a small sample app that demonstrates the problem.

[highprof.zip](https://github.com/w3c/webcodecs/files/7487976/highprof.zip)

**Comment by dalecurtis** [comment]
This sounds like it should be a Chrome bug; we'd expect this to work, but for issues with Chrome please file an issue at https://crbug.com/new and we'll help route that. @sandersdan

**Comment by jamespearce2006** [comment]
Thanks for confirming. That was my suspicion.
