### ISSUE TITLE
Support for SVC scalability modes

### ISSUE THREAD

**Issue by aboba** [w3c/webcodecs#40]
The`VideoEncodeLayer` dictionary is using the approach to SVC used in the [ORTC API](http://draft.ortc.org/#rtcrtpdecodingparameters*).  Unfortunately, this approach cannot support non-hierarchical scalability modes such as K-SVC.  That is why we took a different approach in [WebRTC-SVC](https://w3c.github.io/webrtc-svc/).  Can we instead use an approach based on `scalabiltyModes`?

**Comment by sandersdan** [comment]
A few beginner questions I have about SVC:

- What features require specific decoder support? (My understanding is that a constrained baseline H.264 decoder should be able to decode with a temporal layer stripped out, but that other modes require decoder support.)
- How can sites query for support? Can we simplify the query to a small set of attributes the encoder/decoder has, or do we need the full SVC configuration?
- Is there an existing compatibility matrix for hardware encoder/decoder support that I can reference? (Primarily for Android, but also Windows would be useful.)

**Comment by chcunningham** [comment]
> How can sites query for support? Can we simplify the query to a small set of attributes the encoder/decoder has, or do we need the full SVC configuration?

For H.264, rfc6381 described "svc" as a codec string prefix similar to "avc". I have no idea if this has been used in practice. It would sure be nice if the svc prefix + profile bytes described sets of svc features that must be supported.

For other codecs (VP9, AV1), I'm even less familiar. @marco99zz @jzern

**Comment by jzern** [comment]
@FrankGalligan

Frank, I don't think we defined any codec strings for svc.

**Comment by chcunningham** [comment]
> Frank, I don't think we defined any codec strings for svc.
@sandersdan found that, for H264, they seem to have defined SVC profiles, so that might suggest a path for vpx/av1 (assuming its not deemed integral to some existing profiles - could also be fine with that).

**Comment by FrankGalligan** [comment]
No, unfortunately we did not.

**Comment by aboba** [comment]
@sandersdan 

1. What features require specific decoder support? 
[BA] Today, Chromium only supports SVC with VP8, VP9 and (in-progress) AV1. For these codecs, decoder support for SVC is mandatory, so there is no need to negotiate support for SVC tools.  Since the only browser supporting H.264/SVC was Edge Spartan (current Edge, Chrome, Firefox and Safari only support H.264/AVC), we don't really need to worry about decoder capabilities, at least for browsers (discovering the forwarding capabilities of SFUs is useful, but that is a separate issue). 

2. My understanding is that a constrained baseline H.264 decoder should be able to decode with a temporal layer stripped out, but that other modes require decoder support.

[BA] Since H.264/SVC is only supported in legacy browsers, I don't believe we need to worry about this too much. But for those interested in the history of H.264/SVC interop, it was addressed via the [IMTC H.264/SVC bitstream profile](https://www.mef.net/resources/technical-specifications/download?id=106&fileid=file1), which established mandatory and optional scalability modes for H.264/SVC. 

3. How can sites query for support? Can we simplify the query to a small set of attributes the encoder/decoder has, or do we need the full SVC configuration?

[BA] In WebRTC-SVC we address this by making it possible to query the supported scalabilityMode values of an encoder or decoder. 

4. Is there an existing compatibility matrix for hardware encoder/decoder support that I can reference? (Primarily for Android, but also Windows would be useful.)

[BA] All browsers can decode SVC in VP8 and VP9.  Chromium-based browsers support WebRTC-SVC, currently advertising support for L1T2 and L1T3 scalability modes. I am expecting additional scalability modes to be supported for AV1, such as spatial scalability modes (e.g. L2T2) or K-SVC modes.

**Comment by aboba** [comment]
@chcunningham 

"For H.264, rfc6381 described "svc" as a codec string prefix similar to "avc". I have no idea if this has been used in practice."

[BA] In SDP negotiation, H.264/SVC ([RFC 6190](https://tools.ietf.org/html/rfc6190)) is treated as a distinct codec from H.264/AVC ([RFC 6184](https://tools.ietf.org/html/rfc6184)).  This simplifies things somewhat. 

"It would sure be nice if the svc prefix + profile bytes described sets of svc features that must be supported."

[BA] The IMTC H.264/SVC bitstream profile enables interoperability by mandating that encoders and decoders support a subset of scalability modes (e.g. `L1T2`, `L1T3`, etc.).  Because an H.264/SVC decoder may not be able to decode any scalability mode an H.264/SVC encoder can send, for H.264/SVC it is necessary for both the encoder and decoder to advertise their supported scalability modes. 

"For other codecs (VP8, VP9, AV1), I'm even less familiar." 

[BA] Since VP8/VP9/AV1 decoders can decode anything an encoder can send, all that we need to worry about is discovering what scalability modes an encoder supports and then configuring it to use a supported mode.

**Comment by sandersdan** [comment]
My initial impression is that the WebRTC-SVC approach is simpler (as compared to ORTC) to implement capability detection for. In general I'd like to follow the WebRTC APIs where possible for consistency.

It does seem like there are a lot of modes, and I'm not sure what happens when AV2 comes out and supports an order of magnitude more things. I am in general not a fan of query APIs that list every supported feature, because it often turns out to be expensive to query platform decoders.

Is there already a mapping of this for MediaCapabilities? If so, do clients list the modes they are interested in as part of the query?

**Comment by chcunningham** [comment]
> Is there already a mapping of this for MediaCapabilities? If so, do clients list the modes they are interested in as part of the query?

No, no facility for MC exists at this time. If I understand @aboba  correctly, none is need for vpx/av1. 

> [BA] Since VP8/VP9/AV1 decoders are required to be able to decode anything an encoder can send, there typically isn't a need to discover or configure decoder SVC capabilities, just to discover what scalabilityMode values an encoder supports and to configure an encoder to encode using a desired scalabilityMode.

Where can I read about this requirement? I see that it makes things much easier from a capabilities, but I'd like to be sure its airtight.

**Comment by aboba** [comment]
@sandersdan The ORTC approach was not able to configure or advertise support for non-hierarchical modes like the KEY and KEY_SHIFT modes that are supported in AV1.  It also was more complex for developers to correctly configure, as compared with the WebRTC-SVC approach.  

The only downside of WebRTC-SVC as compared with ORTC was that ORTC supported arbitrary resolution ratios for spatial scalability as well as the ability to enable/disable individual layers.  These features were also available in WebRTC 1.0's simulcast API (via sendEncodings), so developers may come to expect them.  As discussed [here](https://github.com/w3c/webrtc-svc/issues/14), there have been some ideas about how to add some of that functionality back to WebRTC-SVC, at the cost of some increased complexity.

**Comment by aboba** [comment]
@chcunningham While there isn't a need to describe the scalability modes that VP8/VP9/AV1 decoders can decode (because a compliant decoder should be able to decode any mode), there is a need to describe the scalability modes than an encoder can encode.  For example, in Chrome when you enable the "experimental web features" flag, you will. see that [calling RTCRtpSender.getCapabilities('video')](https://webrtc.internaut.com/iit-2020/cap-dumper/) indicates support for `L1T2` and `L1T3` with the VP8 and VP9 codecs, but not spatial scalability modes or the KEY or KEY_SHIFT modes.

**Comment by jimbankoski** [comment]
As per discussions a couple of things we'd like to see : 

per layer level bitrate controls.  
the ability to set min and max quantizer on a per level basis.  
the ability to change the type of scalability on the fly

**Comment by aboba** [comment]
@jimbankoski  Some of these needs have also come up in the WebRTC-SVC specification:
https://github.com/w3c/webrtc-svc/issues/14

**Comment by jimbankoski** [comment]
@adoba Thanks for the pointer and agreed it seems to be covered there!

**Comment by chcunningham** [comment]
Didn't make Q4, but I intend to work on it this quarter.

**Comment by aboba** [comment]
Related: https://github.com/w3c/webcodecs/issues/85

**Comment by chcunningham** [comment]
Triage note: marked 'breaking' because the PR that resolves this makes a breaking change to the encoder output callback in order to emit metadata.

**Comment by chcunningham** [comment]
With #187 merged, the breaking change to the encoder output callback is now resolved. We still intend to add additional descriptions of SVC metadata (frame dependencies, spatial layer id, ...), but this is done by extending the metadata dictionary with new keys for those.

**Comment by juhani-honkala** [comment]
Has there been any progress on this? Is there a browser support matrix for the allowed SVC modes and some working examples how to actually use them or this all still wip?

**Comment by aboba** [comment]
Temporal scalability is supported for VP8, VP9, H.264/AVC and AV1.  A live demo is [here](https://webrtc.internaut.com/wc/wcWorker/). 

Github repo: https://github.com/aboba/wc-demo
