### ISSUE TITLE
How to cache decoded VideoFrames

### ISSUE THREAD

**Issue by ziyunfei** [w3c/webcodecs#401]
```
const decoder = new VideoDecoder({
  output: frame => {
    this.frames.push(frame) // this can lead to stalls

    // copying to canvas can cost time

    // const videoFrame = document.createElement('canvas')
    // videoFrame.width = frame.displayWidth
    // videoFrame.height = frame.displayHeight
    // videoFrame.getContext('2d').drawImage(frame, 0, 0)
    // this.frames.push(videoFrame)
    // frame.close()

    if (this.frames.length === nbSamples) resolve()
  },
```

**Comment by sandersdan** [comment]
There will never be a way to cache frames without at least sometimes making a copy, which will cost time. In the short term that likely means `createImageBitmap()` if you want to use GPU resources or `copyTo()` if you want to use CPU resources.

There is an in-progress proposal for a `copy()` API that will produce a non-stalling `VideoFrame` in one (async) step.
