### ISSUE TITLE
VideoEncoder.isConfigSupported returns boolean?

### ISSUE THREAD

**Issue by Yahweasel** [w3c/webcodecs#403]
I'm writing a polyfill for WebCodecs and found an inconsistency: in the definition for `VideoEncoder`, the spec says that `VideoEncoder.isConfigSupported` returns `Promise<boolean>`, which is inconsistent with all other `isConfigSupported`s, and also the actual description of `VideoEncoder.isConfigSupported` describes returning a `Promise<VideoEncoderSupport>`, which is consistent. I'm assuming this was just a typo, or perhaps an old version that wasn't updated.

**Comment by padenot** [comment]
Yes, good catch, thanks!
