### ISSUE TITLE
Chrome wrong result for ulaw isConfigSupported

### ISSUE THREAD

**Issue by Yahweasel** [w3c/webcodecs#410]
On Chrome (at least, Chrome 96), `AudioEncoder.isConfigSupported` throws an exception for the prehistoric mu-law codecs, while `AudioDecoder.isConfigSupported` says that they're supported. The fact that they're not supported is all fine and good, but throwing isn't spec compliant: `isConfigSupported` is supposed to return an object with `supported: false`, not throw an exception, if the codec is recognized but unsupported. It behaves correctly for unsupported MPEG-1 Layer 3.

```
x = await AudioEncoder.isConfigSupported({codec: "ulaw", sampleRate: 8000, numberOfChannels: 1})
VM74:2 Uncaught TypeError: Failed to execute 'isConfigSupported' on 'AudioEncoder': Unknown codec.
    at <anonymous>:1:24
(anonymous) @ VM74:1
x = await AudioDecoder.isConfigSupported({codec: "ulaw", sampleRate: 8000, numberOfChannels: 1})
{config: {…}, supported: true}
```

P.S.: G.711? Really? I mean, I understand why MPEG-1 Layer 3 is there fighting the bad fight for prehistoric codecs—half the audio hobbyist community is stuck in codec Groundhog Day—but was somebody asking for mu-law?

**Comment by dalecurtis** [comment]
Thanks for the report, please file bugs against Chrome at https://crbug.com/new -- this bug tracker is for spec / standardization issues. If you post the bug number here I'll ensure it gets routed appropriately.
