### ISSUE TITLE
Use of OBU in AV1 WebCodecs registration is incorrect

### ISSUE THREAD

**Issue by cconcolato** [w3c/webcodecs#414]
The AV1 WebCodecs registration at https://w3c.github.io/webcodecs/av1_codec_registration.html uses the following sentence in https://w3c.github.io/webcodecs/av1_codec_registration.html#encodedvideochunk-data:

>  EncodedVideoChunk [[internal data]] is expected to be either an "open bit-stream unit" (OBU) or "low-overhead OBU" as described in Section 5 of [AV1].

The use of "either ... or" is not clear. AV1 defines:
- a generic OBU syntax (section 5.3), which allows to embed or not the OBU size inside the OBU definition.
- the so-called "low-overhead bitstream format" where the size must be present in the OBU definition (as indicated in 5.2). Size of frames and size of temporal units are not explicitly provided.
- the so-called "Length delimited bitstream format" where the sizes of temporal units, frames and OBUs are provided outside of the OBU syntax. 

In practice, the "low-overhead bitstream format" is mostly used.

Also, it seems to indicate that one encoded chunk is a single OBU, which is not possible for key frames for example (you need a sequence header OBU).

I would suggest rephrasing to:
>  EncodedVideoChunk [[internal data]] is expected to be data compliant to the "low-overhead bitstream format" as described in Section 5 of [AV1].

**Comment by dalecurtis** [comment]
I agree, PR created, thanks for filing!
