### ISSUE TITLE
VideoDecoderConfig.spatialScalability

### ISSUE THREAD

**Issue by chcunningham** [w3c/webcodecs#418]
Stemming from https://github.com/w3c/media-capabilities/issues/182#issuecomment-982897152, we probably want a similar knob for WebCodecs. For example, if an implementer's hardware VP9 codec doesn't support reference scaling but your software codec does support it.

**Comment by aboba** [comment]
`referenceScaling` has been changed to `spatialScalability` in MC.

**Comment by aboba** [comment]
@dalecurtis Can we close this? `spatialScalability` is now in the spec.
