### ISSUE TITLE
WebCodecs registration policy

### ISSUE THREAD

**Issue by chrisn** [w3c/webcodecs#426]
In the [last Media WG meeting](https://www.w3.org/2021/12/14-mediawg-minutes.html#t02) we talked about criteria for adding new WebCodecs registrations. @aboba [suggested](https://lists.w3.org/Archives/Public/public-media-wg/2021Dec/0005.html): 

> 1.  Specification required.  This could be a reference to a specification published by an SDO, or a website (e.g. VP9).  There may be some stability requirement (e.g. a reference to a personal github may not qualify).  The specification should be available at least to the designated Expert Reviewer.
> 2.  Expert review required. The expert could be one of the spec editors, or someone designated by the WG Chairs.  The idea is to designate someone to review the proposal and produce a written review with a recommendation (with the reasoning behind it), posted to the WG mailing list.
> 3.  WG discussion.  The WG (and the submitter) should have the opportunity to respond to the expert review.
> 4.  Consensus determination.  The WG Chairs determine whether the Expert review has consensus or not.

**Comment by dalecurtis** [comment]
We now have a VideoFrameMetadata registry.

**Comment by chrisn** [comment]
This issue was about clarifying codec registrations, and we haven't updated the [registry requirements](https://w3c.github.io/webcodecs/codec_registry.html#registration-entry-requirements) based on these suggestions.

The main differences I see are:

1. A stability requirement for the codec specification
2. An explicit expert review step (e.g., as part of step 5 of the requirements). I note that this is where we had difficulty with the proposed H.263 registration

The other points may be already sufficiently covered:

1. Step 1 already requires a link to a public specification
3. WG discussion is implied in step 5 by "If the Media Working Group reaches consensus"
4. Consensus determination is mentioned in step 5, and covered by the [WG charter](https://www.w3.org/2021/07/media-wg-charter.html#decisions)

We could prepare a PR to change the registry document, the main thing needing input would be whether we want to include a stability requirement, and - if we do - how it should be forumulated.
