### ISSUE TITLE
remove excess 2119 language, e.g. in section 13

### ISSUE THREAD

**Issue by samuelweiler** [w3c/webcodecs#428]
I'm seeing some 2119 MAYs et. al. in places where a plain-language "may" (et. al.) may be appropriate, e.g. "An attacker MAY accumulate a codec feature" - that usage doesn't call for the 2119 MAY.  (v. for example, the MAYs in the last paragraph of that section, where they are appropriate.)

**Comment by padenot** [comment]
Sorry, we've been missing this one, this was reported by someone else independently and is now being discussed and fixed in #685.
