### ISSUE TITLE
hardwareAcceleration: prefer-software leads to PPS refer error with new Keyframe

### ISSUE THREAD

**Issue by fyuvb** [w3c/webcodecs#432]
I am writing an application for video editing on web using Webcodecs. I tried different demos online and they worked fine. However, when I am trying to perform transcoding for a long video, I would need to insert key-frames. 

I have an Implementation that insert a key-frame every 100 frames. If use `hardwareAcceleration: prefer-software`, whenever I insert a keyframe, encoding would finish without error. I then mux the video with Mp4box.js. However, during playback using ffplay, first 100 frames played without problem, while it would throw the following error at 100th frame, which is a keyframe.

> [h264 @ 0x7fc05d833400] non-existing PPS 1 referenced    0B f=0/0
> [h264 @ 0x7fc05d833400] decode_slice_header error
> [h264 @ 0x7fc05d833400] no frame!
> [h264 @ 0x7fc05d836200] non-existing PPS 1 referenced    0B f=0/0
> [h264 @ 0x7fc05d836200] decode_slice_header error
> [h264 @ 0x7fc05d836200] no frame!
> ....

and ffplay will start to throw the following error at 200th frame, which is also a keyframe:

> [h264 @ 0x7fc05d837400] non-existing PPS 2 referenced
> [h264 @ 0x7fc05d837400] decode_slice_header error
> [h264 @ 0x7fc05d837400] no frame!
> [h264 @ 0x7fc05d833400] non-existing PPS 2 referenced
> [h264 @ 0x7fc05d833400] decode_slice_header error
> [h264 @ 0x7fc05d833400] no frame!
> ....

If I use `hardwareAcceleration: prefer-hardware` without changing any other code, the video could be encoded and played without errors. It seems to me that the encoded keyframe chunks somehow expect a new PPS but the player cannot find it. Since I did not change other code and config, I suspect this is a webcodecs issue? 

I am using Chrome 97.0.4692.71 with MacOS with Intel Core.

Thanks for any help!

**Comment by dalecurtis** [comment]
This seems like a Chrome specific bug, can you file at https://crbug.com/new instead and post the number here? I'll make sure it's routed appropriately.

**Comment by sandersdan** [comment]
I'm not sure this is a bug necessarily. If you're encoding to AVC format, then the parameter sets are not guaranteed to be in-band, instead you must use the `description` in the `VideoDecoderConfig`. This is in the `EncodedVideoChunkMetadata` that is the second parameter of the output callback.

**Comment by fyuvb** [comment]
> r `ffplay` compatibility it's likely enough to copy the PPS in-band (at every keyframe, otherwise seeking may not work). I think most players support this approach even though it is not technically conformant.

Thanks for the idea. I tried to play with the default player (QuickTime Player) and VLC on MacOS and it also stuck during playback. 

Here is a test video that I created using prefer software encoding with a keyframe per 30 frames.
https://user-images.githubusercontent.com/35753211/150247166-f0f9d9d5-4da2-42c1-8347-7d2024d67dcb.mp4

Also, I found that when using prefer-software, h264 main profile (avc1.640028) is not supported. Only baseline (avc1.42001E) is supported. Is this also expected?

I will probably come up with a demo page and file this issue to chrome later.

**Comment by sandersdan** [comment]
> Also, I found that when using prefer-software, h264 main profile (avc1.640028) is not supported. Only baseline (avc1.42001E) is supported. Is this also expected?

Chrome's software encoder is OpenH264; this is expected.

> I will probably come up with a demo page and file this issue to chrome later.

That would certainly help verify the situation with regards to metadata!

**Comment by onthegit** [comment]
Happens here too, when there a keyframes in the video it gets stuck at the keyframe and can not play.

**Comment by AlexVestin** [comment]
@sandersdan would it be possible to set the [sps/pps strategy](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/media/video/openh264_video_encoder.cc#31) to constant when using the software encoder in WebCodecs? would make it consistent with the hardware implementation and slightly less confusing for newbies like me

**Comment by sandersdan** [comment]
The hardware encoder implementation in Chrome does not guarantee constant parameter sets. They are required to change at resolution changes, but may change more often.

The short answer is no, WebCodecs requires that applications are aware that configurations can change. It's possible that we may want to add a constant mode in the future, but it would not be the default mode, likely would not support hardware, and may not be available on all platforms.
