### ISSUE TITLE
Failed to execute 'configure' on 'VideoDecoder': Failed to parse avcC.

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#442]
when i input the ps_rawData in decoder.configure ,there is an error `Uncaught (in promise) TypeError: Failed to execute 'configure' on 'VideoDecoder': Failed to parse avcC.` ?
var vCfg = {
        codec: "avc1.4D001F",
       description: avcC
        }
so webcodecs only support flv_rawData ?

**Comment by sandersdan** [comment]
I do not know what `ps_rawData` or `flv_rawData` are. The expected format (`AVCDecoderConfigurationRecord`) is described in the registry, https://www.w3.org/TR/webcodecs-avc-codec-registration/#videodecoderconfig-description.
