### ISSUE TITLE
VideoEncoder encode functions doesn't work

### ISSUE THREAD

**Issue by artakpoghosyan1** [w3c/webcodecs#443]
I am using the code sample from [web.dev/webcodecs/#demo](https://web.dev/webcodecs/#demo).
I want to add keyframes in a specific interval here: `const insert_keyframe = (frame_counter % 150) == 0;` and try to record it using `MediaRecorder`.

It records fine, but the problem is that the encoder keyframe interval defaults to every 100 frames. 

Here is my modified code [example](https://glitch.com/edit/#!/upbeat-lizard-wolf?path=video-worker.js%3A33%3A0), which is based on the example above.

Is this a bug or am I doing something wrong?

**Comment by sandersdan** [comment]
`MediaRecorder` is encoding its own stream, independent of WebCodecs. You can inspect `chunk.type` to verify the keyframe rate produced by `VideoEncoder`.
