### ISSUE TITLE
is there some samples to decode the audio raw bitstream by webcodecs ?

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#445]
https://w3c.github.io/webcodecs/samples/

these samples are all decode the video data , so if there is some samples to decode the audio raw bitstream by webcodecs ?

**Comment by chcunningham** [comment]
we don't have one in the samples/ folder yet, but see here for audio decoding (and rendering via AudioWorklet).

https://github.com/chcunningham/wc-talk#simple_video_playerhtml-live-demo

please reopen if you have any follow up questions
