### ISSUE TITLE
Coding Tool configuration

### ISSUE THREAD

**Issue by aboba** [w3c/webcodecs#478]
In codecs such as AV1 there are screen content coding tools that can offer very effective compression for appropriate content. 

The question is how these tools can be configured to be used.  Screen content coding cannot be on by default since it isn't generally useful. Dynamically recognizing when screen content coding would be helpful seems like it would be complex.

The Content-Hints specification is one way to activate screen content coding (or other encoding optimizations), but the hint is currently not passed along when a MediaStreamTrack is used as input to create a stream of VideoFrames.  

Another possibility is to add an attribute to configuration.

**Comment by sandersdan** [comment]
This sounds like something I would expect to be a codec-specific configuration parameter.

We also do not currently have a way to request 4:4:4 and RGB encoding, which applies more generally to other codecs.

**Comment by chcunningham** [comment]
> Another possibility is to add an attribute to configuration.

Editors call: We favor this option for its simplicity.

I grabbed this screenshot of AV1 coding tools from @marco99zz's RTC@Scale talk. @aboba are these what you had in mind? @marco99zz, can you help me prioritize this list in terms of what should be added to WebCodecs.

![unnamed](https://user-images.githubusercontent.com/12039355/162057176-57173bfa-146b-4bcb-9a0d-9abd90b3d00c.png)

**Comment by aboba** [comment]
Yes, was looking for a way to turn on Palette mode & IntraBC.  Being able to control other coding tools would also be useful.

**Comment by marco99zz** [comment]
On Wed, Apr 6, 2022 at 12:43 PM chcunningham ***@***.***>
wrote:

> Another possibility is to add an attribute to configuration.
>
> Editors call: We favor this option for its simplicity.
>
> I grabbed this screenshot of AV1 coding tools from @marco99zz
> <https://github.com/marco99zz>'s ***@***.*** talk. @aboba
> <https://github.com/aboba> are these what you had in mind? @marco99zz
> <https://github.com/marco99zz>, can you help me prioritize this list in
> terms of what should be added to WebCodecs.
>
Sure I can help you prioritize the list for WebCodecs.

**Comment by Djuffin** [comment]
We went with per-codec configuration (see https://github.com/w3c/webcodecs/issues/646 )
But  I'm thinking that we might want a generic content type hint in the VideoEncoderConfig.
At least OpenH264 and libvpx support such hints.

**Comment by aboba** [comment]
Within the Screen Content Community Group (SCCG) we had a discussion of [what libwebrtc does to optimize screen sharing](https://docs.google.com/presentation/d/1RIRPAg-M3pQYTFqL0rDGBIl8bQvLAzq122lWUF5JIy8/).  It varies quite a bit depending on the codec. 

For example, if the track came from a screen share, `SCREEN_CONTENT_REAL_TIME` is set in Open H.264.

**Comment by chrisn** [comment]
Discussion from Media WG meeting on 13 Jun 2023: [minutes](https://www.w3.org/2023/06/13-mediawg-minutes.html#t01).
