### ISSUE TITLE
VideoEncoder performance with hardware acceleration

### ISSUE THREAD

**Issue by dustinkerstein** [w3c/webcodecs#492]
Today I tried to put together a streaming transcoder with WebCodecs. It's functional, and was surprisingly very easy to build, but I am running into some performance issues (and for my use-case, I can't drop frames). To isolate things a bit, I put together a very simple JSFiddle that focuses solely on the VideoEncoder portion of the code. You can find the demo here - https://jsfiddle.net/badru54k/

On my 2018 Macbook Pro, I can only maintain around 25fps. This feels a bit low to me considering it is using the hardware encoder (verified in the Chrome Media tab). With FFmpeg + VideoToolbox,  I can encode 3840x2160 h264 at around 65-70fps. Is this amount of overhead to be expected, or is there maybe something else going on?

Thanks,
Dustin

PS - I can also replicate the same behavior in Edge and in Opera (with slightly worse performance).

**Comment by aboba** [comment]
One thing to keep in mind is that support for hw acceleration can vary with width/height/framerate, etc.  So if you're expecting to be able to encode 3840 x 2160 h264 at 65 fps, you should check whether this is going to be supported via [isConfigSupported](https://w3c.github.io/webcodecs/#videoencoder-interface). [MediaCapabilities API](https://w3c.github.io/media-capabilities/) may also provide useful info (e.g. power efficient, smooth, etc.).

**Comment by dalecurtis** [comment]
This seems likely to be an implementation specific issue. Can you file a crbug.com/new issue instead? This repo is for issues with the spec and samples. It's fine to file issues here if you're unsure where it belongs though.

**Comment by dustinkerstein** [comment]
Thanks for the replies. Yah, it definitely could be an implementation specific issue, and I'll definitely post an issue at the Chromium tracker. But I'm still a little curious - as I imagine WebCodecs is a fairly lightweight wrapper on VideoToolbox (for MacOS), I would expect they would perform similarly. Maybe there's a better way for me to test. If you happen to know offhand, what would be the most performant type of VideoFrame to encode? Ie. CanvasImageSource vs. ArrayBuffer, alpha, pixel format, etc.

Upon another quick test with that JSFiddle (which isn't using isConfigSupported for simplicity) shows that my max encode rate at 1080p is ~80fps, whereas with FFmpeg + VideoToolbox I hit ~280fps. Thanks again!
