### ISSUE TITLE
WebCodecs mp4-decode demo using mp4box.js set codedWidth/codedHeight incorrectly

### ISSUE THREAD

**Issue by dustinkerstein** [w3c/webcodecs#495]
In this demo - https://w3c.github.io/webcodecs/samples/mp4-decode - inside the mp4_demuxer.js file:

```
 async getConfig() {
    let info = await this.source.getInfo();
    this.track = info.videoTracks[0];

    var extradata = this.getExtradata(this.source.getAvccBox());

    let config = {
      codec: this.track.codec,
      codedHeight: this.track.track_height,
      codedWidth: this.track.track_width,
      description: extradata,
    }

    return Promise.resolve(config);
  }
```

`this.track.track_height` and `this.track.track_width` apparently have the DAR already applied, so they're not actually the correct codedWidth/codedHeight which can cause issues with `isConfigSupported`

See here for some additional background - https://bugs.chromium.org/p/chromium/issues/detail?id=1325659

**Comment by dalecurtis** [comment]
Thanks for reporting!

**Comment by dalecurtis** [comment]
@sandersdan

**Comment by sandersdan** [comment]
The correct values should come from the `VisualSampleEntry.width/height` (in the `stsd`) rather than the tack description. It seems like `mp4box.js` puts this in a codec-specific place (eg. in the `stsd.avc1` entry for H.264), but there is also an accessor for it at `track.video.width/height`.
