### ISSUE TITLE
How to cache decoded VideoFrames By CopyTo , is there demo？

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#500]
How to cache decoded VideoFrames By CopyTo , is there demo？

**Comment by onthegit** [comment]
This is is exactly the same question I have: how to make copyTo() work. Copying the attributes of frame and passing them in options as in https://github.com/w3c/webcodecs/issues/501#issuecomment-1162284163
throws error...

**Comment by yangfangfang1204** [comment]
is there a demo that how to use `VideoFrame.copy()` , And What is the return value of the `Video.copy()` ? Is it a shared texture index or shared texture data?

**Comment by sandersdan** [comment]
There is no demo of `copy()` because `copy()` is not yet specified. It would return a new `VideoFrame`.
