### ISSUE TITLE
Failed to construct 'VideoFrame': data is not large enough

### ISSUE THREAD

**Issue by onthegit** [w3c/webcodecs#501]
from the example at https://developer.mozilla.org/en-US/docs/Web/API/VideoFrame/copyTo
```
const buffer = new Uint8Array(videoFrame.allocationSize());
await videoFrame.copyTo(buffer);
videoFrame.close()
```
and then later trying to reconstruct the frame:
```
const frame = new VideoFrame(buffer, options)
```
 I get an error: 
```
Failed to construct 'VideoFrame': data is not large enough
```

Chrome:
Version 101.0.4951.54 (Official Build) (64-bit)
Os: Linux

**Comment by onthegit** [comment]
@sandersdan thank you for your reply. The options are just a copy of the frame attributes as in:
```
 let codedRect: any = null
            if (videoFrame.codedRect) {
              codedRect = {
                ...frame.codedRect,
              }
            }
            const options = {
              buffer: cp,
              codedHeight: frame.codedHeight,
              codedWidth: frame.codedWidth,
              format: frame.format,
              displayHeight: frame.displayHeight,
              displayWidth: frame.displayWidth,
              duration: frame.duration,
              timestamp: frame.timestamp,
              visibleRect: {
                width: allbuf[i].codedWidth,
                height: allbuf[i].codedHeight,
                x: 0,
                y: 0,
              }
            }

       videoFrame.close()
const frame = new VideoFrame(buffer, options)

```

**Comment by sandersdan** [comment]
That would be correct (nit: use `videoFrame.visibleRect` rather than breaking it up) if you passed options to `allocationSize()` and `copyTo()` to use `{rect: videoFrame.codedSize}`.

**Comment by onthegit** [comment]
> That would be correct (nit: use `videoFrame.visibleRect` rather than breaking it up) if you passed options to `allocationSize()` and `copyTo()` to use `{rect: videoFrame.codedSize}`.

Thanks @sandersdan , however it still throws error. Can you make an example on how correctly to copy VideoFrame?
I tried the following for options:
```
{
              codedHeight: videoFrame.codedHeight,
              codedWidth: videoFrame.codedWidth,
              format: videoFrame.format,
              displayHeight: videoFrame.displayHeight,
              displayWidth: videoFrame.displayWidth,
              duration: videoFrame.duration,
              timestamp: videoFrame.timestamp,
              visibleRect: videoFrame.visibleRect,
            }
```
but it still throws error: data is not large enough.

**Comment by sandersdan** [comment]
`copyTo()` is likely to be better than drawing to a canvas and reading back.

`createImageBitmap()` may be better than either, depending on whether the frame is hardware-backed and the amount of available GPU memory.

**Comment by onthegit** [comment]
@sandersdan Thanks for your replies. The problem with copyTo and createImageBitmap is that both are async, while drawImage is synchronous, so will the copyTo and createImageBitmap always be pushed to an array in the correct order (since they are async?)

**Comment by sandersdan** [comment]
You will indeed need to be careful about ordering. `createImageBitmap()` and `copyTo()` are both async specifically because it can make readback of GPU-backed images more efficient.

**Comment by onthegit** [comment]
@sandersdan  thanks. I also commented here: https://github.com/w3c/webcodecs/issues/436#issuecomment-1162392899
Would making the copy() synchronous like drawImage, be more useful?

**Comment by jozefchutka** [comment]
I managed to avoid `Failed to construct 'VideoFrame': data is not large enough` in Chrome 109 by doing:

```ts
// data is VideoFrame
const rect = {x:0, y:0, width:data.codedWidth, height:data.codedHeight};
const arrayBuffer = new ArrayBuffer(data.allocationSize({rect}));
data.copyTo(arrayBuffer, {rect});

const init:VideoFrameBufferInit = {
	codedHeight: data.codedHeight,
	codedWidth: data.codedWidth,
	colorSpace: data.colorSpace,
	displayHeight: data.displayHeight,
	displayWidth: data.displayWidth,
	duration: data.duration || undefined,
	format: data.format!,
	timestamp: data.timestamp!,
	visibleRect: data.visibleRect || undefined
}

// later in code

const frame = new VideoFrame(arrayBuffer , init);
```
