### ISSUE TITLE
what's the best practice for rendering  AudioData from audioDecoder

### ISSUE THREAD

**Issue by exolution** [w3c/webcodecs#507]
what's the best practice for rendering  AudioData from AudioDecoder?
copy to an AudioBuffer？
Is there any other way？ 
and why webcodecs spec dont mention this (just mentioned videoframe rendering by canvas.draw)

**Comment by dalecurtis** [comment]
```
let buffer = new AudioBuffer({
  numberOfChannels: audio_data.numberOfChannels,
  length: audio_data.numberOfFrames,
  sampleRate: audio_data.sampleRate
});
for (var ch = 0; ch < audio_data.numberOfChannels; ++ch)
  audio_data.copyTo(buffer.getChannelData(ch), {planeIndex: ch, format: "f32-planar"});
```

Sorry we don't have a sample for audio decoding in the repro. There should be a test page we created along the way that can be added to the samples. @tguilbert-google

**Comment by tguilbert-google** [comment]
As some starting off points, this demo should have the basics of a WebAudio audio renderer:
https://github.com/chcunningham/wc-talk. It might be out of date however.

If you need a quick an simple solution, you can use a MediaStreamTrackGenerator and an audio element, such as in [this example](https://github.com/web-platform-tests/wpt/blob/master/mediacapture-insertable-streams/MediaStreamTrackGenerator-audio.https.html#L81).

Note that there are limits to the MediaStreamTrackGenerator: if you decode a long audio file and push it all at once, data will be dropped. You should feed in the audio as it plays.

**Comment by padenot** [comment]
> As some starting off points, this demo should have the basics of a WebAudio audio renderer:
> https://github.com/chcunningham/wc-talk. It might be out of date however.

It works well afaik.
