### ISSUE TITLE
`VideoFrame.copyTo` doesn't resolve its `Promise` with a value

### ISSUE THREAD

**Issue by padenot** [w3c/webcodecs#510]
We want to resolve with the `sequence<PlaneLayout>`: we compute the underlying values but we don't use them.

**Comment by Djuffin** [comment]
For consistency it's probably worth doing something similar for `AudioData.copyTo()`?
For example return a computed version of `AudioDataCopyToOptions`

**Comment by padenot** [comment]
This PR is about the fact that the prose wasn't matching the interface, intent and implementation. `AudioData.copyTo` has never returned anything because it would return something that's trivial.
