### ISSUE TITLE
Incorrect computation in `Compute Layout and Allocation Size` when figuring out the destination rect

### ISSUE THREAD

**Issue by padenot** [w3c/webcodecs#511]
In [Compute Layout and Allocation Size](https://w3c.github.io/webcodecs/#videoframe-compute-layout-and-allocation-size), [sourceLeftBytes](https://w3c.github.io/webcodecs/#computed-plane-layout-sourceleftbytes) is calculated by doing `parsedRect.x / sampleWidthBytes`, which is equal to `parsedRect.x / (sampleWidth * sampleBytes)`. This is dividing coordinates in display space by a multiplication of coded space times the width of the sample in bytes (so in bytes).

Shouldn’t this be `(parsedRect.x / sampleWidth) * sampleBytes` ? Similarly for `sourceWidthBytes`.

**Comment by sandersdan** [comment]
This algorithm no longer lines up exactly with the Chromium implementation, so it's hard to say exactly what the original intention was. Your interpretation seems correct to me.

We have a rectangle within the coded region (`parsedRect`), already verified to be sample-aligned, and we're dividing by the sub-sampling factor (`sampleWidth`/`sampleHeight`) to find the coordinates within the current plane. From that the offsets can be computed by multiplying with `sampleBytes`.
