### ISSUE TITLE
VideoDecoder is not defined    

### ISSUE THREAD

**Issue by badcode06** [w3c/webcodecs#514]
Hi all. I have just cloned the repo and then created a local server. 
when I try to run the mp4-decode sample I got the following error:

```
Uncaught ReferenceError: VideoDecoder is not defined
    at demux_decode_worker.js:27:17
```
so what might be the problem?

**Comment by dalecurtis** [comment]
Are you serving the page from a secure context or from localhost? What browser version are you using?

**Comment by badcode06** [comment]
using https solved the problem. thanks.
