### ISSUE TITLE
 visibleRect validation for VideoFrame{Buffer}Init seems wrong

### ISSUE THREAD

**Issue by ChunMinChang** [w3c/webcodecs#515]
[Validate VideoFrameInit](https://w3c.github.io/webcodecs/#validate-videoframeinit) and [Validate VideoFrameBufferInit](https://w3c.github.io/webcodecs/#valid-videoframebufferinit) return false when visibleRect.y + visibleRect.height >= codedHeight in step 1-5 and step 3 respectively, or visibleRect.x + visibleRect.width >= codedWidth in step 1-6 and step 4 respectively, while [Parse Visible Rect](https://w3c.github.io/webcodecs/#videoframe-parse-visible-rect) returns false when overrideRect.y + overrideRect.height > codedHeight or overrideRect.x + overrideRect.width > codedWidth. Shouldn’t [Validate VideoFrameInit](https://w3c.github.io/webcodecs/#validate-videoframeinit) and [Validate VideoFrameBufferInit](https://w3c.github.io/webcodecs/#valid-videoframebufferinit) return false in the “>” case instead of “>=”?  A VideoFrame{Buffer}Init value with a visibleRect whose (x, y, width, height) = (0, 0, 2, 2), codedWidth=2 and codedHeight=2 seems valid.

**Comment by sandersdan** [comment]
Sounds correct to me; the inequality should be strict.
