### ISSUE TITLE
Codecs string is ambiguous ? What are the supported profile and level

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#520]
What is the highest resolution supported by WebCodecs? i play the video with 5520(width)*2400(height) , it can not play , and the error is `Failed to execute configure on VideoDecoder :Codecs string is ambiguous` ?
So if the resolution is so high that the video can not play ? or other reason ?

**Comment by sandersdan** [comment]
This error message means that you `codec` field is not supported or in the correct format. Resolution was not considered.
