### ISSUE TITLE
Why the VideoFrame.duration  is always null?

### ISSUE THREAD

**Issue by exolution** [w3c/webcodecs#521]
the spec said that VideoFrame.duration is copied from EncodeVideoChunk.duration
but i found it is always null even the input EncodeVideoChunk.duraion has been setted.(eg. 40000)
i test this at Chrome 103.0.5060.134

![image](https://user-images.githubusercontent.com/3261425/182995764-b14ffd37-431b-4267-a666-8b79829d19c6.png)
![image](https://user-images.githubusercontent.com/3261425/182995854-5254c5cb-7253-4598-8876-568aa65d919d.png)

**Comment by sandersdan** [comment]
Confirmed, Chrome's implementation is not copying the duration through from `EncodedVideoChunk` to `VideoFrame`.

I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1352565.
