### ISSUE TITLE
there is a  memory leak when decode video by webcodecs repeatedly?

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#522]
when i decode viedeo by webcodecs , and close the VideoDecoder , and new the VideoDecoder, the memory is growth ?
so when i stop decode , how can i release the webcodecs decoding resources ?

**Comment by sandersdan** [comment]
As long as both the `VideoFrame` objects and the `VideoDecoder` object are closed, memory growth is not expected. If you can reproduce such growth, please file a Chromium bug.
