### ISSUE TITLE
add audio encoder frame duration configure parameter

### ISSUE THREAD

**Issue by bdrtc** [w3c/webcodecs#526]
we use webcodecs audio encoder encode opus realtime and send via webtransport,  but find its frame duration（ptime） is 60ms by default and no parameter to configure it.
60ms is not acceptable for realtime stream,  it add extra 40ms fix delay compare to webrtc's 20ms ptime, hope the configure for audio ptime to encoder parameter

**Comment by sandersdan** [comment]
Agreed, there should probably be a configurable parameter for packet duration.

**Comment by bdrtc** [comment]
close this as resoled by #551
