### ISSUE TITLE
add opus inbandfec & dtx configure parameter to webcodecs audio encoder configure

### ISSUE THREAD

**Issue by bdrtc** [w3c/webcodecs#527]
webcodecs support many audio codecs, some codec has its private encode configure parameters, opus for example, inbandfec、 dtx、complexity is importent for realtime comunication, but we find those paramerter was not described in spec and no brower implement them currently,
we sugguest the spec describe a method for such case.

**Comment by aboba** [comment]
Duplicate of https://github.com/w3c/webcodecs/issues/244

**Comment by bdrtc** [comment]
close this as solved via #594
