### ISSUE TITLE
audio-video-player sample support seek?

### ISSUE THREAD

**Issue by shaozj** [w3c/webcodecs#533]
I saw the new audio-video-player sample. It's really a great work to me. I wonder could you provide a seek sample? The video player would be much more useable.

**Comment by sandersdan** [comment]
I think that seeking adds a lot of complexity to the demuxer without adding much in terms of WebCodecs. It's probably better to build a video player as an external project rather than as a WebCodecs sample.

**Comment by shaozj** [comment]
@sandersdan  Thanks! I will try to build a video player based on WebCodecs.

**Comment by chcunningham** [comment]
Awesome!

FYI, the high level steps for player.seek(T) would be
1) seek the demuxer to the key frame at-or-before time T
2) reset() the decoder and decode from that key frame, continuing until you reach T
3) discard decoder outputs until you get the frame at time T
4) keep playing as usual
