### ISSUE TITLE
Progressive loading for textures

### ISSUE THREAD

**Issue by munsocket** [w3c/webcodecs#54]
In WebGL applications we facing with issue that downloading from server and loading texture to GPU is pretty slow operation. In web we have progressive JPEG/WEBP but we can't access to level of details and need to create 2-4 versions of a file each of which laready has progressive format.

![](https://habrastorage.org/webt/sa/mz/ed/samzedbihjuuv2zr6d8hgktciog.png)

In same WebGPU issue https://github.com/gpuweb/gpuweb/issues/766 they suggested to me Basis and your repo. But looks like basis should be smaller in size or inside js fetch API?

**Comment by sandersdan** [comment]
The mipmap bias is outside the scope of WebCodecs (or really any spec, it's part of the app/engine), but progressive loading in general is being considered as part of the ImageDecoder API.

That is being discussed in https://github.com/dalecurtis/image-decoder-api/issues/3.

**Comment by munrocket** [comment]
This could be a good improvement, feels like webgl/webgpu not so good as page render without it.

**Comment by dalecurtis** [comment]
Thanks for the link. It's good to know folks would be interested in this.

**Comment by munrocket** [comment]
This is not popular, but works like charm.
I wonder why we still doesn’t have it.
Texture load for 4k images takes lot of time.

**Comment by chcunningham** [comment]
The ImageDecoder spec is now landed with facilities for decoding progressive images from a readable stream off the network. 
https://w3c.github.io/webcodecs/#typedefdef-imagebuffersource

I don't think there's another clear action item for WebCodecs here. Please re-open if I've overlooked anything.
