### ISSUE TITLE
WPT tests lack HEVC

### ISSUE THREAD

**Issue by sandersdan** [w3c/webcodecs#543]
I didn't offhand have HEVC samples to use for these, they should be added.

**Comment by StaZhu** [comment]
Done. https://github.com/w3c/webcodecs/pull/695

**Comment by aboba** [comment]
@Djuffin @padenot In #695, HEVC samples were added.  There are also [some HEVC tests in WPT](https://wpt.fyi/results/webcodecs?label=experimental&label=master&aligned). 

Can we close this?
