### ISSUE TITLE
Webcodecs performance bottleneck

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#553]
in one tab page, i create sixteen canvases to play video.
eight play video by webcodecs decode and eight play video by webassembly soft decoding.
then i find the eight video by webcodecs  don't flow smoothly, and the VideoDecoder.DecodeQueueSize is bigger.
`output1 cb decodeQueueSize:79,wid:1920,hei:1088,timestamp:576282,length:0
output1 cb decodeQueueSize:79,wid:1920,hei:1088,timestamp:576282,length:0
 output1 cb decodeQueueSize:68,wid:1920,hei:1088,timestamp:576762,length:0
 output1 cb decodeQueueSize:81,wid:1920,hei:1088,timestamp:576242,length:0
 output1 cb decodeQueueSize:80,wid:1920,hei:1088,timestamp:576322,length:0
 output1 cb decodeQueueSize:80,wid:1920,hei:1088,timestamp:576322,length:0
output1 cb decodeQueueSize:80,wid:1920,hei:1088,timestamp:576322,length:0
output1 cb decodeQueueSize:68,wid:1920,hei:1088,timestamp:576802,length:0
output1 cb decodeQueueSize:82,wid:1920,hei:1088,timestamp:576282,length:0
output1 cb decodeQueueSize:80,wid:1920,hei:1088,timestamp:576362,length:0`

but if i play sixteen video by webcodecs decode , the sixteen video is all flow smoothly .

so why ?

**Comment by dalecurtis** [comment]
Please file implementation issues for Chrome at https://crbug.com/new -- this repo is for spec issues. Please provide your chrome://gpu information and a sample showing the problem when you file there.
