### ISSUE TITLE
seek is slower than video element

### ISSUE THREAD

**Issue by shaozj** [w3c/webcodecs#557]
I implemented seek based on webcodecs and mp4box.js. However, I found it's slower than video element's seek. My implementation is like follows:

1. seek the demuxer to the key frame at-or-before time T
2. reset() the decoder and decode from that key frame, continuing until you reach T
3. discard decoder outputs until you get the frame at time T
4. keep playing as usual

How can I imporve the speed of seek?

**Comment by dalecurtis** [comment]
Your logic seems correct and should mirror what we do internally in Chrome. This sounds like an implementation issue, so if this is Chromium please file a bug at https://crbug.com/new with a sample showing the issue.

**Comment by shaozj** [comment]
Is there any optimize in chrome internal video implementation?

**Comment by dalecurtis** [comment]
What you're doing sounds exactly the same as what we do internally. We don't have any "fast seek" type optimizations.

**Comment by shaozj** [comment]
I tested videodecoder's decode speed based on the sample of this repo. When seek a frame，the average decode time is about 5.8ms while video element seek the same frame, the average decode time is about 3ms.
![image](https://user-images.githubusercontent.com/7326406/189283282-ce24d66a-2adb-4309-8f7b-401f15adcf12.png)

**Comment by shaozj** [comment]
When I config hardwareAcceleration to 'prefer-hardware', the browser tells the config is not support.
