### ISSUE TITLE
1200W is no picture in cpu: I5-7500 gpu: intel Graphics630 chrome: V105

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#577]
we use webcodecs hard decode the 1200W(w:4000*h:3000) video , and VideoDecoder.isConfigSupported return supported , but there is no picture, no frame output in win10 cpu: I5-7500 gpu: intel Graphics630 chrome: V105 ?

**Comment by padenot** [comment]
This sounds like an implementation bug, please file a bug in the vendor's bug tracker:

- WebKit (Safari): https://bugs.webkit.org/enter_bug.cgi?product=WebKit&component=Web%20Audio (WebKit bugzilla account needed).
- Blink (Chrome): https://new.crbug.com/ (Google account needed).
- Gecko (Firefox): https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Web%20Audio (GitHub or Mozilla Bugzilla account needed).
