### ISSUE TITLE
which engine called by webcodecs in windows?

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#578]
we know win7 only support d3d9 , win10 support d3d9 and d3d11 . so webcodecs called which one when hard decode video ?

**Comment by padenot** [comment]
This sounds like a question related to a particular implementation or configuration, please ask the browser vendor, this is an issue tracker for the specification. I don't know which venue would be best for this question, or if the information is readily available somewhere.

@dalecurtis, maybe you can help here?

**Comment by dalecurtis** [comment]
For questions about Chromium's media engine you can write to [media-dev](https://groups.google.com/a/chromium.org/g/media-dev)

Chromium will use D3D11 on Windows 8+ and MFT / D3D9 / D3D11 as available on Windows 7 systems.
