### ISSUE TITLE
WebCodec using VP9 codec, SVC and variable bitrate mode, does not adhere to given desired bitrate.

### ISSUE THREAD

**Issue by kalradivyanshu** [w3c/webcodecs#584]
Chrome Version       : 106.0.5249.119 (Official Build) (64-bit) (cohort: Stable Installs & Version Pins)
URLs (if applicable) : https://codepen.io/kalradivyanshu/pen/OJZqKve
Other browsers tested:
  107.0.5304.36 (Official Build) beta (64-bit) (cohort: Beta) FAIL
  109.0.5362.0 (Official Build) canary (64-bit) (cohort: Clang-64) FAIL
  
have tested this issue:
       Edge: 106.0.1370.47 (Official build) (64-bit) FAIL

### What steps will reproduce the problem?
(1) Start a video encoder with SVC setting L1T3, codec: vp09.00.10.08, bitrateMode: variable and bitrate: 2500000, then encode a 1080p30fps video.
(2) Calculate the bitrate of the encoded video by using the encodedChunk's byteLength property

### What is the expected result?
The bitrate should be within reasonable limit of 2.5mbps

### What happens instead?
The bitrate is consistantly above 19mbps (for this video: https://www.youtube.com/watch?v=hmE9f-TEutc, shared via getDisplayMedia) and gets to as high as 55mbps+.

### Please provide any additional information below. Attach a screenshot if possible.
This issue only happens for vp9 (both profile 0 and profile 2) + variable bitrateMode + SVC (L1T2 or L1T3 both).

If we set the bitrateMode to constant, it adheres to the bitrate recommendation, if we turn off SVC mode, it works even with variable bitrateMode.

For VP8, it works for all SVC modes, and all bitrate mode, the problem is specifically for VP9.

We were able to get this error on chrome stable, beta, canary, and edge stable.

Here is the reproducable codepen: https://codepen.io/kalradivyanshu/pen/OJZqKve .
Click on any of the button, and give permission to access your screen, and it should start working.
We made the attached tables by sharing the tab playing this youtube video: https://www.youtube.com/watch?v=hmE9f-TEutc.

It was reproducable in other youtube videos also, as long as there is motion on screen, since those have a higher bitrate.

The stats shown are the average bitrate of the last 2 seconds of video, the deltaframe size and keyframe size are average size since the begining of the video.
### VP8 constant bitrate SVC
![vp8_const_svc](https://user-images.githubusercontent.com/12642750/196041191-e86cea86-a8a3-42a1-a56f-3b35821e09f3.jpg)
### VP8 variable bitrate SVC
![vp8_variable_svc](https://user-images.githubusercontent.com/12642750/196041189-f73cc383-e30d-46da-84ee-b4082f311814.jpg)
### VP9 constant bitrate SVC
![vp9_const_svc](https://user-images.githubusercontent.com/12642750/196041186-f577963c-673d-48ae-aece-2c27406153ac.jpg)
### VP9 variable bitrate SVC
![vp9_variable_svc](https://user-images.githubusercontent.com/12642750/196041193-83c1c15d-74e2-40a7-99ea-72f99fbbb789.jpg)

**Comment by aboba** [comment]
@kalradivyanshu I have seen something similar, with VP9 producing encoded chunks the size of keyframes, even when a delta frame was requested.  Interestingly, this did not seem to happen when latencyMode of "quality" was requested.

**Comment by dalecurtis** [comment]
The chromium bug tracker looks like the right place for this.
