### ISSUE TITLE
framerate vs frameRate

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webcodecs#588]
[`VideoEncoderConfig` uses lower-case `framerate`](https://w3c.github.io/webcodecs/#dom-videoencoderconfig-framerate) (as does media capabilities), when [other specs ](https://dontcallmedom.github.io/webdex/f.html#frameRate%40%40screen-capture%25%25dfn)(screen capture, media capture and streams, webxr) use the camel-case `frameRate`.

Aligning would be an improvement from a developer ergonomics perspective

**Comment by padenot** [comment]
Too bad, but it's a bit late at this point indeed. I assume this attribute sees a lot of use out there.

**Comment by dontcallmedom** [comment]
the future being longer than the past, can we move to frameRate and have implementation provides a backwards compat layer?

**Comment by dalecurtis** [comment]
I don't mind accepting both, but defer to @padenot @aboba @youennf.

**Comment by youennf** [comment]
bitrate is a similar field in VideoEncoderConfig and is consistently lower cased in all APIs AFAIK.
Is it fine to have frameRate but bitrate in the same dictionary?

**Comment by dalecurtis** [comment]
We seem to use `bitrate` everywhere AFAICT. `bitrate` does seem to have "formal" recognition from dictionaries though: https://www.merriam-webster.com/dictionary/bit%20rate whereas I can't find an equivalent for `framerate`.

I personally prefer `framerate` and `bitrate` but am always sympathetic to consistency arguments.

**Comment by dalecurtis** [comment]
A similar CamelCase or flatcase issue is coming up with https://github.com/w3c/webcodecs/pull/594

**Comment by Djuffin** [comment]
I don't think we'll be renaming anything at this point. So let's live with what we have.
