### ISSUE TITLE
Should serialisation steps throw DataCloneError instead of TypeError in case forStorage is true

### ISSUE THREAD

**Issue by youennf** [w3c/webcodecs#589]
Chrome and Safari are throwing DataCloneError in that case (see https://github.com/web-platform-tests/wpt/pull/36567 and https://github.com/WebKit/WebKit/pull/5576).
Should we align spec to the implementations?
This might be applicable to EncodedVideoChunk, EncodedAudioChunk, AudioData and VideoFrame.

**Comment by padenot** [comment]
Yes, it seems better semantically. We're currently implementing this, and we'll throw a `DataCloneError` instead, so everybody is aligned.

**Comment by dalecurtis** [comment]
Thanks for fixing!
