### ISSUE TITLE
there is memory leak that render webcodecs frame  by webgl?

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#611]
use the sample to test ,i find there is memory leak render by webgl in win10/win8_ChromeV107 ,but there is no memory leak in win7_ChromeV107 . and there are no memory leak render by 2d in win10/8/7-ChromeV107 ?
https://github.com/w3c/webcodecs/tree/main/samples/video-decode-display

so this is a chrome bug ?

**Comment by dalecurtis** [comment]
Yes, please check to see if the issue reproduces on Chrome Canary. If not please file a bug at https://crbug.com/new
