### ISSUE TITLE
decode hevc return upsupported 

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#614]
`let config = {
              codec: "hvc1.1.6.L123.00",
            };
            VideoDecoder.isConfigSupported(config).then((configInfo) => {
              console.info(`%c1>your browser support 265 hard Decoder`, 'color: green');
            }).catch(() => {
              console.warn(`%c1>your PC does not support 265 hard Decoder but support 264, if you want to hard decode 265 ,try to update the GPU driver`, 'color: red');
  });`

when i decode the 265 video by webcodecs, VideoDecoder.isConfigSupported() return supported. but when i input 265 video data , it report the error: 
hardDecode reportError:Unsupported configuration. 
Check isConfigSupported() prior to calling configure().
state:closed,frameRate:25

some GPU driver update to 2022 , it could play the 265 . and some GPU driver update the latest ，it still cant play 265(above NVIDIA GTX950).

so why it return supported, but cant play ?
and why it need the latest(2022) graphics driver ？

**Comment by bdrtc** [comment]
This should be impl issue of browser, instead of this draft.

**Comment by StaZhu** [comment]
Can you fire a crbug issue, with `chrome://gpu` information attached? 

Probably  because of an exiting issue (https://bugs.chromium.org/p/chromium/issues/detail?id=1384481) fixed in M109, you can download chrome canary to test again if you are referrring to chrome browser here.

**Comment by yangfangfang1204** [comment]
ok , i test in chrome canary , it did return unsupported , 
and the second question is  why it need the latest(2022) graphics driver ？

**Comment by StaZhu** [comment]
> ok , i test in chrome canary , it did return unsupported , and the second question is why it need the latest(2022) graphics driver ？

Please move our conversation to `crbug.com` if you may have any future question, thanks!
