### ISSUE TITLE
Inconsistent SVC metadata between WebCodecs and WebRTC Encoded Transform API

### ISSUE THREAD

**Issue by aboba** [w3c/webcodecs#619]
Currently the [`EncodedChunkMetadata` dictionary](https://w3c.github.io/webcodecs/#encoded-video-chunk-metadata)  includes `SvcOutputMetadata`, which only supports temporal scalability ([temporalLayerId](https://w3c.github.io/webcodecs/#dom-svcoutputmetadata-temporallayerid)).  

However, within the Encoded-Transform API, [RTCEncodedFrameMetadata](https://www.w3.org/TR/webrtc-encoded-transform/#RTCEncodedVideoFrameMetadata) includes its own (incompatible) SVC metadata. 

Here is a comparison of the two approaches:
https://docs.google.com/presentation/d/1lFAUSvApbBYfBNJH_xcRW0YjD0aF5T1ZqjyyDJMesJw/edit#slide=id.g1a4ac56601a_3_0

Can we define the complete set of SVC metadata in WebCodecs and then have it inherited by Encoded Transform? 

Related: https://github.com/w3c/webrtc-encoded-transform/issues/170

**Comment by dalecurtis** [comment]
+1 for consistency, but defer to @djuffin

**Comment by Djuffin** [comment]
It's unusual to add fields unless there is at least one implementation that makes use of them. But in this case compatibility with Encoded Transforms seems like a pretty good reason to add these fields.

I think we can even rename `SvcOutputMetadata` into something more relevant to video frames, `Output` doesn't seem to convey a lot of meaning outside of webcodecs' context.

**Comment by aboba** [comment]
The [Encoded Transform metadata](https://w3c.github.io/webrtc-encoded-transform/#dictdef-rtcencodedvideoframemetadata) has now been updated.  However, it still is not completely compatible with the [WebCodecs extended SVC metadata proposal](https://docs.google.com/document/d/1O6kxAQPLWhCRHkH-6zutcqEUOUWRS6NFM2CQAvi1VTg/). 

Should we submit a PR based on what is in the original WebCodecs proposal?  Or are any changes needed?

**Comment by dalecurtis** [comment]
ed note: @aboba to send PR and @Djuffin to review.

**Comment by aboba** [comment]
**A summary of where we are now.** 

Here is the [`RTCEncodedVideoFrameMetadata` dictionary](https://www.w3.org/TR/webrtc-encoded-transform/#RTCEncodedVideoFrameMetadata): 

![image](https://user-images.githubusercontent.com/808811/216474849-7615268b-684d-4da0-8734-54056b476d2e.png)

Here is what is in [WebCodecs Section 6.7:](https://w3c.github.io/webcodecs/#encoded-video-chunk-metadata) 

![image](https://user-images.githubusercontent.com/808811/216474935-7b30e424-f18d-4c01-a0bf-6eb9b7a17583.png)

Here is what was in the extended WebCodecs SVC metadata proposal: 

![image](https://user-images.githubusercontent.com/808811/216475175-6d3674fe-e327-4b0e-9bfd-6ac446d9cfa7.png)

**Comment by aboba** [comment]
@pthatcherg @alvestrand Can you take a look?

**Comment by chrisn** [comment]
Minutes from 11 Apr 2023 Media WG meeting: https://www.w3.org/2023/04/11-mediawg-minutes.html#t03
