### ISSUE TITLE
In ubuntu, the webcodecs don't support 'prefer-hardware'

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#621]
In ubuntu, i find if i set webcodecs config(hardwareAcceleration) is  'prefer-hardware',it report a error:
hardDecode reportError:Unsupported configuration. Check isConfigSupported() prior to calling configure().,state:closed,frameRate:25

and it could play 264-video by  'prefer-software'.and it still could not play 265-video until ChromeVV108.0.5359.98.

the report of chrome://gpu :
[ChromeV108.0.5359.98-GTX10603gb.txt](https://github.com/w3c/webcodecs/files/10207342/ChromeV108.0.5359.98-GTX10603gb.txt)

so why linux-chrome could not hard decode 264-video?

And when webcodecs could  hard decode 265-video in linux-chrom？

**Comment by dalecurtis** [comment]
Linux chrome doesn't support hardware video decoding in many cases. Please file Chromium bugs at https://crbug.com/new

**Comment by webpawn** [comment]
@yangfangfang1204 i had the same question，did you resolve it？
