### ISSUE TITLE
VideoEncoder is unsupported in Android Chrome and other mobile browsers

### ISSUE THREAD

**Issue by purplekidlouis** [w3c/webcodecs#627]
Hi, I just test VideoEncoder with `if ('VideoEncoder' in window) {console.log('VideoEncoder is supported');}` in Android Chrome, Edge, Opera. It seems to be unsupported in all the mobile browsers, but the VideoFrame is supported. 
If there is a correct way to call VideoEncoder, welcome to point out, thanks!
The version of Android Chrome is 108.0.5359.128.

**Comment by dalecurtis** [comment]
VideoEncoder is only available on secure context, so if you're just opening the new tab page and using inspect to do this or hosting on http that's not localhost/127.0.0.1/etc, you won't see it supported.
