### ISSUE TITLE
Windows: Encoding 1920px (Portrait) Frame Not Possible with High Profile avc codec

### ISSUE THREAD

**Issue by JoeHorvath95** [w3c/webcodecs#629]
Cannot encode with web codecs VideoEncoder and a portrait resolution of 1920x1080 on Windows with a high profile h264 codec e.g. avc1.640034

Console error: Failed to execute 'encode' on 'VideoEncoder': Cannot call 'encode' on a closed codec.

Codepen: https://codepen.io/JoeHorvath/pen/eYjeWLX

From what I understand about profiles and levels this codec should be able to handle a resolution of this size and it works on mac but on Windows it only seems possible using baseline codecs

**Comment by dalecurtis** [comment]
Please file Chrome implementation bugs at https://crbug.com/new and we can take a look. Please include the chrome://gpu information.
