### ISSUE TITLE
do we need support specify audio encode bitrateMode interface ?

### ISSUE THREAD

**Issue by bdrtc** [w3c/webcodecs#649]
some audio codecs(opus, HE AAC) support specify  encoder bitrate mode, 

according [section-2.1.8 of opus rfc6716](https://datatracker.ietf.org/doc/html/rfc6716#section-2.1.8) and [opus api doc](https://www.opus-codec.org/docs/html_api/group__encoderctls.html#ga34d09ae06cab7e1a6c49876249b67892) , 
opus encoder support VBR and CBR mode, and vbr was used by default.

we can use [bitrateMode exist in mediastream-recording](https://www.w3.org/TR/mediastream-recording/#enumdef-bitratemode), 
`constant` correspond to CBR and `variable` correspond to VBR mode. 

suggest to add `audioBitrateMode` in audio codec that support vbr/cbr mode,   which specifes the [BitrateMode](https://www.w3.org/TR/mediastream-recording/#enumdef-bitratemode) that should be used to encode the audio track.

**Comment by tguilbert-google** [comment]
This seems reasonable. I can edit the spec and codec registries in Q2.

Thanks for the suggestion!
