### ISSUE TITLE
Need to make dictionary members more consistent in coding style?

### ISSUE THREAD

**Issue by helaozhao** [w3c/webcodecs#658]
just as the members in [opus-encoder-config](https://www.w3.org/TR/webcodecs-opus-codec-registration/#opus-encoder-config). There's a kind of style of CamelCase, such as _frameDuration_, and a kind of style of flatcase as well.

Does there still have an opportunity to make them consistent, like in camel case?

**Comment by tidoust** [comment]
Thanks for the report. Closing as duplicate as I think this is being tracked in #588. Feel free to reopen (or complete #588) if I missed something!

**Comment by helaozhao** [comment]
> Thanks for the report. Closing as duplicate as I think this is being tracked in #588. Feel free to reopen (or complete #588) if I missed something!

I think there is a little different in that #588 mainly discusses the attribute _bitrate_, and it looks that there has got an agreement ( _bitrate_ is proper in style).
In this issue I referred to the attributes in [opus-encoder-config](https://www.w3.org/TR/webcodecs-opus-codec-registration/#opus-encoder-config), especially the attributes of [_packetlossperc_](https://www.w3.org/TR/webcodecs-opus-codec-registration/#dom-opusencoderconfig-packetlossperc) and [_useinbandfec_](https://www.w3.org/TR/webcodecs-opus-codec-registration/#dom-opusencoderconfig-useinbandfec).
It's great if has chance to change them.

**Comment by chrisn** [comment]
These opus attributes were previously discussed here: https://github.com/w3c/webcodecs/pull/594/files/f133d9401d90191f7de543cadfe0b3ae8acf2b42#r1001142719

Personally, I would prefer `packetLossPerc`, `useInbandFec`, `useDtx` (or should that be `useInbandFEC` and `useDTX`, following [suggested casing rules](https://www.w3.org/TR/design-principles/#casing-rules)?)

**Comment by bdrtc** [comment]
one question: as w3c spec, we should follow the [casing-rules ](https://www.w3.org/TR/design-principles/#casing-rules) of w3c  or follow special codec RFC ? I prefer follow w3c design principles personally.
