### ISSUE TITLE
VideoFrame needs an way to export pixels into ImageData

### ISSUE THREAD

**Issue by Djuffin** [w3c/webcodecs#660]
`VideoFrame`s can have multiple pixel formats depending on where they come from. 
 Currently `VideoFrame.copyTo()` doesn't do format conversions and can only export data in the same pixel format.
It's a bit complicated to spec and implement universal format conversion in `copyTo()`  (https://github.com/w3c/webcodecs/issues/92)

Most image/video processing libraries (for example opencv.js and tensorflow.js) accept `ImageData` as an input. 
So it makes sense to remove the format conversion burden from website/app developers and introduce a way to  read-back `VideoFrame`s into `ImageData` converting pixel format to RGBA along the way.

Something like
`VideoFrame.copyToImageData(imagedata, x, y)`
`imagedata` the `ImageData` to read to and to get `width` and `height` of the rectangle from which the ImageData will be extracted.
`x` and `y` - coordinates of the top-left corner of the rectangle from which the ImageData will be extracted.

Most likely most developers currently achieve the same result by drawing the frame on the canvas and calling `CanvasRenderingContext2D.getImageData()` later. But it introduces unnecessary copies along the way.

**Comment by dalecurtis** [comment]
I think we'd just have `copyTo` reject the promise with a not supported error if the target format isn't supported. We could also add a `canCopyTo(dict)` method to solve 2 if needed.

**Comment by sandersdan** [comment]
If we're sure we can determine format support synchronously, we could also have `allocationSize()` throw on unsupported format.

**Comment by Djuffin** [comment]
Closing this in favor of https://github.com/w3c/webcodecs/issues/92#issuecomment-1533820212
