### ISSUE TITLE
Low fps when use MediaRecorder in webgl

### ISSUE THREAD

**Issue by blueRaining** [w3c/webcodecs#661]
when i use MediaRecorder  in webgl,and stream from canvas, 
const stream = this._canvas.captureStream(25);
this._mediaRecorder = new MediaRecorder(stream, 
            { 
 
            mimeType: "video/webm;codecs=h264",
             videoMaximizeFrameRate: true
            
            });
in my computer,It's half fps before initialization MediaRecorder,can you help me

**Comment by Djuffin** [comment]
Please report this issue to your browser's bug tracking system. For example for chrome this ishttps://bugs.chromium.org/p/chromium/issues/list.
