### ISSUE TITLE
Undersaturated output in the webcodec sample: video decode display (with WebGPU renderer and 4K video)

### ISSUE THREAD

**Issue by kalradivyanshu** [w3c/webcodecs#665]
I cloned this repo and ran the webcodec video decode display sample, it worked fine for the provided 720p video, I wanted to push it so I got a 4k video (attached below) and it was okayish for 2D, webgl and webGL2 but for WebGPU the video is undersaturated and bright. 
For WebGL/2D the colors were muted and a bit off, but for WebGPU it looked really bad:

Original:
![image](https://user-images.githubusercontent.com/12642750/232484594-7649eee6-6429-41f4-9f51-99b59383dc8e.png)

WebGL2:
![image](https://user-images.githubusercontent.com/12642750/232482164-8b371f7f-4e49-4d77-ad80-eedc780124b4.png)

WebGPU:
![image](https://user-images.githubusercontent.com/12642750/232482219-fb907331-4e5d-4c52-b47c-ddcf028414f6.png)

Original:
![image](https://user-images.githubusercontent.com/12642750/232484512-90900c39-088d-47a1-8799-2e3b83a16679.png)

WebGL2:
![image](https://user-images.githubusercontent.com/12642750/232482345-c03d16e3-11eb-47f9-8993-e219f24c4154.png)

WebGPU:
![image](https://user-images.githubusercontent.com/12642750/232482474-3483bcc6-0b56-4896-ab6d-12bb07da16db.png)

Steps to reproduce:
1. Clone this repo
2. Change the video decode demo to use this video instead: [costa_rica_4k30.mp4](https://user-images.githubusercontent.com/12642750/232482739-1e70ec6f-d21b-46d0-9a55-9b41662d212f.mp4)
3. Run with WebGL, and 2D, the colors will be muted in comparison to original video
4. Run with WebGPU, the colors will be undersaturated and the video will looks very bright.

Maybe this is an issue with mp4box? Is it an issue with webcodec or in the rendering step? 

Browser version:
Microsoft Edge | 113.0.1774.9 (Official build) beta (64-bit)
Revision | 75fed22f252b880b85dc803f70378286843487c5
Chromium version | 113.0.5672.24
Operating system | Windows 11 Version 22H2 (Build 22621.1555)
JavaScript | V8 11.3.10.3

GPU info: [Graphics Feature Status.txt](https://github.com/w3c/webcodecs/files/11250086/Graphics.Feature.Status.txt)

**Comment by dalecurtis** [comment]
This seems like a chromium bug, please file at https://crbug.com/new -- I suspect you need HDR canvas enabled to work with HDR content. I don't think we have a tone-mapping stage in the draw path otherwise.

**Comment by dalecurtis** [comment]
Yes that's correct AFAIK.

You'd need your own tone mapping shader you apply with WebGL/WebGPU. You can see Chrome's here:
https://source.chromium.org/chromium/chromium/src/+/main:ui/gfx/color_transform.cc;l=1138?ss=chromium&q=ToneMap
