### ISSUE TITLE
Estimating Percent of Users That Will Have Hardware Support for h265/hevc

### ISSUE THREAD

**Issue by seflless** [w3c/webcodecs#668]
I'm trying to understand which and how many users will and won't have hardware support for hevc/h265. Does anyone have any more information on which desktop Windows/macOS/Chrome OS consumer devices are likely to have hardware support or not?

**Comment by dalecurtis** [comment]
All macOS users will have support. Most Windows users will too. Most ChromeOS users will not. If you have a launched product with active users, I recommend querying `isConfigSupported` to see the metrics for your user base.

In any case this isn't an issue, so closing.

**Comment by seflless** [comment]
Thanks Dale! Want to follow best practices, so where would you recommend asking questions like this next time? I assumed others would have similar questions.

**Comment by dalecurtis** [comment]
I think the discussions section instead of issues would be appropriate.
