### ISSUE TITLE
Signaling codec resource exhaustion (formerly Custom error types)

### ISSUE THREAD

**Issue by Djuffin** [w3c/webcodecs#669]
Currently WebCodecs rely on DOMExceptions with different names, but DOMException names are [deprecated](https://webidl.spec.whatwg.org/#idl-DOMException-error-names) . 
For proper and granular error reporting WebCodecs might need a special error type, like WebGpu [pipeline error](https://www.w3.org/TR/webgpu/#gpupipelineerror).

We might also need a special error type for rejecting promises and reporting errors via VideoEncoder and VideoDecoder callbacks.

**Comment by chrisn** [comment]
Looking at [the list of DOMException names](https://webidl.spec.whatwg.org/#idl-DOMException-error-names) it's only `IndexSizeError`, `InvalidAccessError,` `TypeMismatchError`, and `URLMismatchError` that are marked as deprecated. The WebCodecs spec doesn't use any of those so I think we're OK in that regard.

**Comment by aboba** [comment]
Can we use `EncodingError` to indicate an issue with the data provided to the Encoder/Decoder, and something else (e.g. `OperationError`) to indicate a resource issue (e.g. hardware encoder resource no longer available),

**Comment by xingri** [comment]
@Djuffin, @aboba  If it is possible, can I get a reference on the current working in progress? 
Would like to investigate any possible changes on application side.

**Comment by chrisn** [comment]
Discussed in Media WG meeting, 30 May 2023, [minutes](https://www.w3.org/2023/05/30-mediawg-minutes.html#t03).

**Comment by padenot** [comment]
None.

**Comment by Djuffin** [comment]
I'm looking at how to suffice signal that we ran out of HW encoders or decoders.
Most logical behavior seems simply reporting [QuotaExceededError](https://webidl.spec.whatwg.org/#quotaexceedederror)
and then I realized that it's basically [Resource Reclamation](https://www.w3.org/TR/webcodecs/#resource-reclamation), that we already have in the spec.

So we don't even need to change much. But we'll need to adjust the definition of the active encoder/decoder i.e. declare newly created encoder/decoder that hasn't outputted anything yet - inactive. Then UA will be able to *reclame* it immediately after it realized that there is no system resources for it.

**Comment by aboba** [comment]
@Djuffin Reading Section 11: Resource Reclamation section, I had some a question:
- "Additionally, User Agents MUST NOT reclaim an [active](https://www.w3.org/TR/webcodecs/#active-codec) [background](https://www.w3.org/TR/webcodecs/#background-codec) codec if it is... An [AudioDecoder](https://www.w3.org/TR/webcodecs/#audiodecoder), when its tab is audibly playing audio."
- 
[BA] So if the audio is not audible (e.g. the remote peer muted for more than 10 seconds and/or internal DTX was triggered), then audio decoders can be reclaimed?  Implication is that codecs need to support CN to avoid reclamation.

**Comment by padenot** [comment]
@aboba I wouldn't expect any implementation to have a reclamation policy for audio codecs -- they are not often using hardware, which often has limited slots. This is mostly about video. Besides, at least in Gecko, a page that makes use of WebRTC facilities (intentionally hand wavy here) is considered active, because the alternative could be dramatic as you note.

I think we should change the prose to make that clearer.

**Comment by aboba** [comment]
With respect to Video, there is currently a debate in WEBRTC WG as to whether a muted camera should result in sending no video frames or whether black frames should be sent instead (e.g. @1 fps).  Here the argument is tilting in favor of not sending video.  This could result in reclamation but that might not be a bad thing (lower energy consumption for the sender and receiver, if you're not sending/receiving frames, why not let the encoder/decoder be reclaimed, etc).

**Comment by padenot** [comment]
Why not? It's because there's a chance that in the future when you need to, you won't be able to, and that's bad UX.
