### ISSUE TITLE
add some function to list audio/video codecs available with webcodecs on a device

### ISSUE THREAD

**Issue by 0-mandrixx-0** [w3c/webcodecs#675]
with the variety of devices and operating systems and the fact the codec implementation is not the same on all platforms, it's quite hard to guess which codec can be used on a device. the only way I've found until now is to check every item in a small list of codec strings I've compiled from examples found accross the internet.

that's why it would be very handy to have a method that lists the audio and video codecs that can be used with webcodecs on a device

thanks

**Comment by 0-mandrixx-0** [comment]
ok. that's a shame I'm still in the darkness. I have no idea of which codecs I could use. there's no real list of codec strings to test. I'v tried the strings of the specs (like flac, mp3, pcm-f32) and nothing works except the mp4a strings and opus. and its only opus on mobile which not a good option if you want to play the file anywhere.
Would you have any clue to find out the codec strings that could be available on a particular device ?

**Comment by Djuffin** [comment]
Currently Chromium only supports Opus and AAC (on Windows and Mac)
