### ISSUE TITLE
How can i get yuv data from a VideoFrame with NV12 format?

### ISSUE THREAD

**Issue by jhl13** [w3c/webcodecs#687]
How can i get yuv data from a VideoFrame with NV12 format? Any samples?

**Comment by sandersdan** [comment]
This would be better in the discussions section, I don't believe it is a spec issue. Closing.

To answer the question, you can get NV12 data using `frame.copyTo()` if the frame already has `frame.format == 'NV12'`.

Adding conversions from other formats is issue #92.
