### ISSUE TITLE
WebCodecs WPT tests do not have reviewers

### ISSUE THREAD

**Issue by youennf** [w3c/webcodecs#692]
As can be seen in https://github.com/web-platform-tests/wpt/pull/40691 and https://github.com/web-platform-tests/wpt/pull/40721, no reviewer is suggested for webcodecs WPT PRs.

We probably need to update https://github.com/web-platform-tests/wpt/blob/master/webcodecs/META.yml to suggests some reviewers.

I can volunteer myself from WebKit side.
On Chromium and Mozilla side, who would be willing to help?
@sandersdan, @padenot maybe?

**Comment by gsnedders** [comment]
There's two parts here: who can be a WPT reviewer (and really we're pretty lax, any member of the WG probably qualifies, plus also anyone with commit access to a major browser), and who wants to be in the set of GitHub users added automatically as a reviewer for changes touching `webcodecs/`.

I'm happy to go ahead and do the former for anyone who volunteers; for the latter maybe just file a PR for the `META.yml` @youennf linked above?

**Comment by sandersdan** [comment]
Sure, I can handle some WebCodecs WPT reviews.

@Djuffin, how about you?

**Comment by Djuffin** [comment]
@gsnedders I can be a WPT reviewer for webcodecs

**Comment by youennf** [comment]
@gsnedders, can you add @sandersdan and @Djuffin?
I can update the `META.yml` file.

**Comment by gsnedders** [comment]
> @gsnedders, can you add @sandersdan and @Djuffin?

They now both have pending invites.

**Comment by Djuffin** [comment]
Both Dan and I joined the group. I guess we can close the issue now.
