### ISSUE TITLE
Specify AudioEncoderConfig.bitrateMode default

### ISSUE THREAD

**Issue by tguilbert-google** [w3c/webcodecs#699]
`AudioEncoderConfig.bitrateMode` [[spec link](https://w3c.github.io/webcodecs/#dom-audioencoderconfig-bitratemode)] does not specify a default value.

Whether a codec uses VBR or CBR varies between codecs, **and between encoders**. Some default values for various encoders:
- Opus: [VBR by default](https://www.opus-codec.org/docs/html_api/group__encoderctls.html#ga34d09ae06cab7e1a6c49876249b67892:~:text=0%20CBR-,1%20VBR%20(default),-The%20configured%20bitrate)
- Windows MediaFoundation AAC: [CBR by default](https://learn.microsoft.com/en-us/windows/win32/medfound/mfpkey-vbrenabledproperty)
- MacOS AudioToolkit AAC: [ABR by default](https://developer.apple.com/library/archive/technotes/tn2271/_index.html#:~:text=other%20encoding%20modes.-,Average%20Bit%20Rate%20(ABR)%20%2D%20Default%20Mode,-%2D%2D%20Recommended%20for%20controlling)

Variations in the default behavior for different codecs _might_ make sense, if it was a well known that a codec uses `VBR` or `CBR` by default. Such details could be added to the codec registry. However, it is confusing if there are variations in the default behavior when using the same codec, with different encoders under the hood.

**Proposal:**
Set `AudioEncoderConfig.bitrateMode = "variable"` as default.

This would technically be a breaking change for AAC encoders, which do not default to VBR.

**Comment by dalecurtis** [comment]
VideoEncoder also defaults to variable, so that seems reasonable to me.

**Comment by bdrtc** [comment]
The [`media recorder spec`](https://w3c.github.io/mediacapture-record/#dom-mediarecorderoptions-audiobitratemode) also defaults to `variable` audio bitrateMode,  it seems reasonable, sugguest to add `defaulting to "variable"`  text hint .

**Comment by Djuffin** [comment]
@tguilbert-google Could you please prepare a PR for this?
