### ISSUE TITLE
VideoDecoder and Intra Refresh?

### ISSUE THREAD

**Issue by warvstar** [w3c/webcodecs#710]
Is it possible to decode an h264 or AV1 stream with intra refresh instead of I frames? When I switch to using intra refresh (through ffmpeg or nvenc) the decoder crashes as its expecting a keyframe.

**Comment by dalecurtis** [comment]
I think this is a duplicate of #650.

@sandersdan

**Comment by sandersdan** [comment]
Yes I believe this is the same request.
