### ISSUE TITLE
Can't use AVC video codecs on mp4 1920x1080 resolution

### ISSUE THREAD

**Issue by a-adly** [w3c/webcodecs#715]
I'm trying to apply AVC codec level 4 for encoding mp4 videos with size 1920x1080 

```
videoEncoder.configure({
      codec: "avc1.640028", // or "avc1.64001E"
      width: 1920,
      height: 1080,
});
```

but always receive this error

`Failed to execute 'encode' on 'VideoEncoder': Cannot call 'encode' on a closed codec.`

Is there another avc codec supported or different settings to be able to encode big size video

**Comment by dalecurtis** [comment]
If this is an issue in Chrome please file a bug at https://crbug.com/new with the details from chrome://gpu -- this succeeds on Chrome desktop for me. If it's Safari you can file an issue at https://bugs.webkit.org/

**Comment by a-adly** [comment]
OK thanks @dalecurtis, yes  in chrome://gpu report it says

> Graphics Feature Status
> Canvas: Hardware accelerated
> Canvas out-of-process rasterization: Disabled
> Direct Rendering Display Compositor: Disabled
> Compositing: Hardware accelerated
> Multiple Raster Threads: Enabled
> OpenGL: Enabled
> Rasterization: Unavailable
> Raw Draw: Disabled
> Video Decode: Hardware accelerated
> Video Encode: Unavailable
> Vulkan: Disabled
> WebGL: Hardware accelerated
> WebGL2: Unavailable
> WebGPU: Hardware accelerated

but encoding works good for smaller size videos 1280x720

I'll try on different device with recent version of Chrome or fill a bug as you suggested

**Comment by Djuffin** [comment]
Works fine on my machine. Please file a bug against Chromium with more details.

**Comment by dalecurtis** [comment]
You'll want to look at the "Video Acceleration Information" section of chrome://gpu to see what the supported resolutions are. If this is Android, resolution supported if very limited.

**Comment by aboba** [comment]
You can try different resolutions [here](https://webrtc.internaut.com/wc/wcWorker2/).  FWIW, I'm not seeing any issue with encoding 1920 x 1080 resolution @ 30 fps with codec string "avc1.42002A".

**Comment by a-adly** [comment]
Tried on a different machine & codec "avc1.640028" worked good


I've tried to encode mp4 videos on this [example here](https://codepen.io/Zero07/pen/ZEVBqNG) taken from a source [muxer library repo](https://github.com/Vanilagy/mp4-muxer)


> You'll want to look at the "Video Acceleration Information" section of chrome://gpu to see what the supported resolutions are. If this is Android, resolution supported if very limited.

yes it was showing empty info on encoding part


> You can try different bitrates and resolutions [here](https://webrtc.internaut.com/wc/wcWorker2/). FWIW, I'm not seeing any errors when encoding 1920 x 1080 resolution with codec string "avc1.640028".

"avc1.640028" was giving same error on my 1st PC:
```
DOMException: Encoder initialization error.
Uncaught DOMException: Failed to execute 'encode' on 'VideoEncoder': Cannot call 'encode' on a closed codec.
    at encodeVideoFrame
```
but worked good on a different machine.

Also codec "avc1.42002A" seems working good on all machines

Thank you all, the issue was coming from the 1st machine I've tried on
