### ISSUE TITLE
`contentHint`: notes aren't normative and shouldn't describe normative behaviour

### ISSUE THREAD

**Issue by padenot** [w3c/webcodecs#735]
I just found a tab with my review of https://github.com/w3c/webcodecs/pull/729 unsubmitted, so I'm opening this new issue with my comments:

See [`contentHint`](https://w3c.github.io/webcodecs/#dom-videoencoderconfig-contenthint):

> NOTE: Any codec-specific encoding options take precedence over [contentHint](https://w3c.github.io/webcodecs/#dom-videoencoderconfig-contenthint).

This seems to be a requirement, but is in an informative note, and that's not correct. We want to describe in what case and which codec-specific option overrides this `contentHint`. Also, we might want this for audio, e.g. we could make it map to those Opus flags: https://github.com/xiph/opus/blob/master/include/opus_defines.h#L191-L199

**Comment by tguilbert-google** [comment]
I will be submitting a PR to add `contentHint` to `AudioEncoderConfig`, for that specific Opus use case.

Should we then add text in the registries, and have the main spec defer to the registries?
