### ISSUE TITLE
frame.copyTo error in mac-chromeV118

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#736]
In MAC-ChromeV108 , it work . but in mac-chromeV118 ,it error

**Comment by sandersdan** [comment]
If you are reporting an issue with Chrome, please file a bug at https://bugs.chromium.org/p/chromium/issues/entry. We'll also need more information, such as the code of the application, the actual error messages, and possibly the media content being used. Feel free to note the bug number here one you have done so.

**Comment by yangfangfang1204** [comment]
Example:
const options = {
    format: imageFrame.format,
    colorSpace: 'display-p3',
    sourceRect: { x: 0, y: 0, width: displayWidth, height: displayHeight },
    destinationOffset: { x: 0, y: 0 }
}
imageFrame.copyTo(yuvFrameBuffer, options).then(() => {
    console.log("2 yuvLength:" + yuvLength + ",displayWidth:" + displayWidth);
    resolve({ yuvFrameBuffer, yuvLength, displayWidth, displayHeight, yuvType });
}).catch(() => {
    console.log("imageFrame copyTo error");
});

the imageFrame is VideoDecoder output
