### ISSUE TITLE
webcodecs encode h264/h265 Capability set

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#745]
chrome://gpu

we could find Chrome webcodecs only support h264 (32x32 to 1920x1088).
so when support hevc ？(decode has support hevc)
when support h264(4096x4096)?

**Comment by Djuffin** [comment]
Chrome doesn't have plans to support HEVC encoding in the near future. 
the same goes for increasing max frame size for AVC encoding.

Please report Chrome bugs and feature requests: https://bugs.chromium.org/p/chromium/issues/list
