### ISSUE TITLE
key-frame request handling when scalability mode is not L1T1 for encoder

### ISSUE THREAD

**Issue by taste1981** [w3c/webcodecs#760]
when encoder is configured to work in L1T2, L1T3, etc, Spec should clarify when a key-frame request is configured for current frame, how this should be handled when current frame is not at base temporal or spatial layer.

For example, should encoder simply reset the GOP structure to T0 and generate a key frame at T0;  or it should reject the key-frame encoding request; or it should record this key-frame request and continue output a delta-frame, and apply the key-frame request till  next base layer frame.

**Comment by Djuffin** [comment]
> reset the GOP structure to T0 and generate a key frame at T0
we should spec this

**Comment by Djuffin** [comment]
UA certainly shouldn't reject key-frame requests regardless of configured scalability mode and the current frame layer

**Comment by taste1981** [comment]
@Djuffin in this case shall spec require going to T0 immediately, or queue the key-frame request till next base layer frame?

**Comment by Djuffin** [comment]
> shall spec require going to T0 immediately, or queue the key-frame request till next base layer frame?

immediately

[VideoEncoderEncodeOptions.keyFrame](https://www.w3.org/TR/webcodecs/#dom-videoencoderencodeoptions-keyframe) corresponds to the frame given to [VideoEncoder.encode()](https://www.w3.org/TR/webcodecs/#dom-videoencoder-encode) thus its should be effective immediately.

**Comment by aboba** [comment]
If there is no specification change needed, can we close this issue?

**Comment by taste1981** [comment]
> Is there is a specification change needed?
> 
> If not, can we close this issue?

Sure. I think this can be closed.
