### ISSUE TITLE
Clarify the `Clone configuration` algorithm

### ISSUE THREAD

**Issue by padenot** [w3c/webcodecs#762]
When looking a `Clone Configuration`, and after having found a bug in Gecko, [a DOM developer said](https://bugzilla.mozilla.org/show_bug.cgi?id=1874293#c6):

> This looks very underspecified in the spec. For one, I don't think any spec defines what assign a copy of config[m] to clone[m]
> means. And either that can throw exceptions, and it should be specified what needs to happen, or it doesn't and we need to 
> figure out what to do in our implementation.

It can throw an exception, a minimal test case (adapted from our bug) would be:

```js
var buf = new ArrayBuffer(4);
buf.transferToFixedLength()
VideoDecoder.isConfigSupported({"codec": "፝a", "description":buf})
```

Chromium says: 

```
Uncaught (in promise) TypeError: Failed to execute 'isConfigSupported' on 'VideoDecoder': description is detached.
```

which makes sense to me, but we need to spec it.

**Comment by padenot** [comment]
Meaning checking if an exception has been thrown, and rejecting the promise.

**Comment by padenot** [comment]
Same deal with `VideoDecoder.configure()` with a detached array buffer. Curiously the configuration isn't cloned in this case, but the same behaviour in Chrome (which I also find sensible).

**Comment by sandersdan** [comment]
Conceptually this could also be part of the `valid VideoDecoderConfig` algorithm, which makes sense for something throwing a `TypeError`.

**Comment by Djuffin** [comment]
I agree that it does sound like a part of config validation
