### ISSUE TITLE
VideoFrameBufferInit metadata field missing

### ISSUE THREAD

**Issue by Yahweasel** [w3c/webcodecs#773]
The constructor for ArrayBuffer construction of a VideoFrame implies in step 21.11 that init should have a metadata field, but the linked metadata field is in VideoFrameInit, not VideoFrameBufferInit, and this field is missing in VideoFrameBufferInit.

Irrelevant since metadata isn't actually used anywhere, but, uhh, there it is :shrug:

**Comment by padenot** [comment]
Merged -- closing this.
