### ISSUE TITLE
`ImageBufferSource` should be `[AllowShared]`

### ISSUE THREAD

**Issue by padenot** [w3c/webcodecs#799]
This is what [Chromium implements](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/webcodecs/image_decoder_init.idl;l=7), but isn't in the spec. We're implementing like Chromium in Firefox, but we need to make the spec say that.

@dalecurtis, anything to add based on implementation experience? I see that it can either transfer or copy, so we should be good for TOCTOU issues and related common problems.

**Comment by dalecurtis** [comment]
Ah yeah, it should be AllowShared. Thanks!
