### ISSUE TITLE
Include some frame info with `VideoDecoder` Errors?

### ISSUE THREAD

**Issue by snosenzo** [w3c/webcodecs#811]
As far as I can see the DOMException passed to the `error` callback on the `VideoDecoder` constructor for failing to decode a frame only provides `error.name = "EncodingError"` and `error.message = "DecodingError"`. This leaves a lot to be desired in terms of trying to debug the data being decoded. I understand that it's hard to give more info due to fingerprinting (as discussed here: #643), but I was wondering if it would be possible to reference the frame that caused the error somehow? Decoding is asynchronous and can build up an internal queue of frames before processing (as far as I can tell, given lack of 1-in 1-out support), it's not possible to know which of the `EncodedVideoChunk`s was responsible for causing that error. It would be great if a part (like the timestamp) or the whole `EncodedVideoChunk` could attached to the error in some way in order to determine the problematic frame.

If this still is at risk of fingerprinting, then no worries and feel free to close the issue.

**Comment by dalecurtis** [comment]
We probably can't attach more in the generated error, but usually the media dev tools for each browser will have more information. In chrome you can find them either in the [Dev Tools panel](https://developer.chrome.com/docs/devtools/media-panel) or under chrome://media-internals.

**Comment by snosenzo** [comment]
Thought so, thanks for your response!
