### ISSUE TITLE
Wrong chroma values in videoFrame.copyTo() on Intel MacOS

### ISSUE THREAD

**Issue by jkosir** [w3c/webcodecs#815]
`videoFrame.copyTo()` returns only zeroes for all chroma values when using hardware accelerated `VideoDecoder`, happens on Intel based Macs only, works as expected on ARM-based Macs.

Reproduction link: https://jsfiddle.net/un3682zp/1/

![videoFrameWrongChroma](https://github.com/w3c/webcodecs/assets/1890480/6d9b8b1b-88d5-42a1-8a7c-e639345c8e96)

Also submitted as a chromium bug: https://issues.chromium.org/issues/351644570, duplicating here as I'm owndering if the issues is with the implementation of frame copying?

**Comment by padenot** [comment]
Please don't file implementation issues in the issue tracker of the standard.
