### ISSUE TITLE
Do Linear PCM AudioDecoders not work?

### ISSUE THREAD

**Issue by Vanilagy** [w3c/webcodecs#821]
Hey guys,

not sure if I'm missing something extremely obvious, but I am incapable of constructing an `AudioDecoder` that decodes Linear PCM. I am aware that there is not much to decode, but [the registration](https://www.w3.org/TR/webcodecs-pcm-codec-registration/) states these codecs exist to provide "passthrough decoding" and a unified code path, which is exactly the case for me.

This fails:
```ts
let decoder = new AudioDecoder({ output: () => {}, error: e => console.error(e) });
decoder.configure({ codec: 'pcm-s16', numberOfChannels: 2, sampleRate: 48000 });
```
```
DOMException: Unknown or ambiguous codec name.
```

It also fails equally for `pcm-u8`, `pcm-s24`, `pcm-s32` and `pcm-f32`.

I'm on Windows 11 with Chrome Version 126.0.6478.128 (Official Build) (64-bit).

**Comment by sandersdan** [comment]
I am not aware of any browser implementing these codecs. See also https://github.com/w3c/webcodecs/discussions/792.

**Comment by padenot** [comment]
Firefox does but our implem hasn't shipped just yet.

**Comment by dalecurtis** [comment]
Can you add some WPT tests for them Paul? We'll update Chromium to match Firefox behavior in the near term then.

**Comment by Vanilagy** [comment]
Thanks for the info, and too bad these codecs aren't supported yet (especially since they're the simplest). I guess I'll code my own "decoder" in the meantime, shouldn't be too hard to do!

**Comment by padenot** [comment]
> Can you add some WPT tests for them Paul? We'll update Chromium to match Firefox behavior in the near term then.

Yes, this is absolutely planed.

**Comment by padenot** [comment]
https://phabricator.services.mozilla.com/D218943, some tests here (that pass in Fx). We'll add more eventually, but it feels to me that sorting out the encoder delay / padding, and then testing all codecs by checking that decoding is correct is a better approach.

**Comment by dalecurtis** [comment]
Thanks, filed https://crbug.com/359102844

**Comment by Vanilagy** [comment]
Same goes for `AudioEncoder`:

![CleanShot 2024-08-13 at 09 17 04@2x](https://github.com/user-attachments/assets/de0a0ef4-f4ff-41aa-89a2-8151b581b0bb)

Strangely, the error message here is different and somewhat misleading, as there's nothing wrong with the channel count. Substituting `pcm-s16` for `opus` makes this code valid.
