### ISSUE TITLE
VideoDecoder sometimes returns invalid VideoFrame data (timing/concurrency sensitive)

### ISSUE THREAD

**Issue by bradedelman** [w3c/webcodecs#837]
Running
Chrome Version 128.0.6613.138 (Official Build) (arm64)

Chip: Apple M1 Max
Memory: 64 GB RAM
macOS 13.5.2 (22G91)

In our application, we want to make concurrent use of VideoDecoders, get VideoFrames, use VideoFrame.copyTo to get the data, and then later use that data to construct VideoFrames.

We find that sometimes, the data produced by copyTo is different (despite it being for the same frame) and that when passed to the VideoFrame constructor, this exception is thrown:

TypeError: Failed to construct 'VideoFrame': Invalid layout. Plane 1 overlaps with plane 0.

It was difficult to isolate this to a small, standalone example, but we've done our best.  The fact that setTimeout's are needed, and that hundreds of concurrent Decoders are needed to show the problem reliably is interesting, though we've seen it happen intermittently in more reasonable circumstances.  The example we are providing is just the best we could do at a standalone example that reliably reproduces the problem.  Open the page, open the Dev console, and if you don't see it fail, try a few page refreshes.  We can see it fail almost 100% of the time with this program, though we also sometimes see other errors as well.

A related issue that it's unclear how long it's safe to hold a reference to a VideoFrame returned by the onFrame callback of the VideoDecoder.  On the one hand, we believe we cannot hold it too long or the decoder will stall.  On the other hand, VideoFrame.copyTo is async, and has no guaranteed timespan.   Not entirely clear how to reconcile those 2 things without a better understanding.

Anyway, we think there's a timing/concurrency bug in the VideoDecoder that this example helps demonstrate.  More than happy to field any follow up questions / help in any way we can.

(it's an HTML file with JavaScript and video data as JSON... but github wouldn't allow uploading it as html file, so just added .txt at the end):
[DecodeBug.html.txt](https://github.com/user-attachments/files/17064746/DecodeBug.html.txt)

**Comment by Djuffin** [comment]
Reported a bug against Chromium: https://issues.chromium.org/u/0/issues/368222755

**Comment by sandersdan** [comment]
> On the one hand, we believe we cannot hold it too long or the decoder will stall. On the other hand, VideoFrame.copyTo is async, and has no guaranteed timespan.

You can close the frame immediately after initiating `copyTo()`. The async process holds its own reference to the underlying frame data.

**Comment by sandersdan** [comment]
I believe this is caused by assuming that the `copyTo()` copies the `codedRect`, but in fact it copies the `visibleRect` by default. I wrote slightly more detail in the Chromium bug.
