### ISSUE TITLE
one mp4 video could play by webcodecs in chromeV129, but couldn't play in ChromeV130

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#843]
https://github.com/user-attachments/assets/5a8e9def-b540-458d-8e10-591e136e35a8

the attach mp4 video ' C62416451.mp4' could play by webcodecs in chromeV129, but couldn't play in ChromeV130
it happen in webcodecs hard decode.

**Comment by Djuffin** [comment]
This issue [has already filed](https://issues.chromium.org/issues/375876224) on Chromium bug tracker. 
Please refrain from using this project for reporting Chromium bugs. It is intended for discussing webcodecs spec.
