### ISSUE TITLE
Problems encountered with using webcodec to decode H265

### ISSUE THREAD

**Issue by AAT290** [w3c/webcodecs#844]
I'm using webcodec to decode an H265 file on the Google Chrome version of 130，The error message is “Decoding error: EncodingError: Decoding error.”，But decoding the same file is normal on the Google Chrome version of 129，I wonder how to locate the cause of this problem

**Comment by sandersdan** [comment]
Please direct issue with Chrome to the Chromium bug tracker. (I suspect this is https://issues.chromium.org/issues/375876224)
