### ISSUE TITLE
Dynamic dropping/enabling of layers for SVC

### ISSUE THREAD

**Issue by marco99zz** [w3c/webcodecs#85]
This is done in webrtc with vp9 by setting target bitrate to 0 for the layer to be disabled, and it can be done anywhere in stream and without key frame. Is this feature supported for SVC?

**Comment by aboba** [comment]
The target bitrate approach has been discussed, but it isn't clear how difficult this would be to implement, particularly for more complex scalability nodes (e.g. K-SVC). 

Related to:
Issue https://github.com/w3c/webrtc-svc/issues/4
Issue https://github.com/w3c/webrtc-svc/issues/14

**Comment by aboba** [comment]
@marco99zz We have now added metadata as well as scalabilityMode configuration.  So if you want to change the scalabilityMode (e.g. from L1T3 to L1T2), you can do that.  Using metadata, the application can identify layers, and then decide what to do with them.  So if an application wants to stop or start sending one or more layers (but doesn't want to change the encoder scalability mode), it can identify the layer(s) it doesn't want to send (or wants to start sending again).

**Comment by chcunningham** [comment]
re: bitrate, the thinking is our top level config.bitrate will describe the base layer. we can revisit bitrate for other layers later, but it seems complicated enough that we may not want it.

**Comment by chcunningham** [comment]
triage note: marking 'extension'. As noted above, current proposals (to add metadata) are extensions. If we later pursue the ability to control bitrate per layer, this too would be an extension.
