### ISSUE TITLE
Complex coding modes (simulcast, SVC, Opus FEC, etc.)

### ISSUE THREAD

**Issue by steveanton** [w3c/webcodecs#9]
This is a tracking issue for designing a solution for complex coding modes supported by various audio/video codecs like simulcast, SVC, and FEC.

**Comment by pthatcherg** [comment]
In particular, we need good SVC support and Bernard mentioned that the "dependsOn" currently in https://github.com/pthatcherg/web-codecs/blob/master/webidl.txt isn't sufficient.

**Comment by mfoltzgoogle** [comment]
Are these coding modes a stable part of the codec specifications (i.e. unlikely to change in the future) or something that applications are able to customize using lower level encoders?

**Comment by pthatcherg** [comment]
I believe they are stable (OPUS and VP9 certainly are), but it sounds like AV1 is very flexible so we need to figure out what modes people would want to use and which we can support.

**Comment by aboba** [comment]
At this point, the [AV1 bitstream specification](https://aomediacodec.github.io/av1-spec/av1-spec.pdf) (including the list of scalability modes in Section 6.7.5) should be considered stable.  The [AV1 RTP payload specification](https://aomediacodec.github.io/av1-rtp-spec/) is still work-in-progress. 

In particular, the K-SVC modes (which are a hybrid of SVC and simulcast) cannot be expressed via "depends on" semantics. The L3T3_KEY mode is shown below:

![L3T3_KEY](https://user-images.githubusercontent.com/808811/72006834-4c9ffc80-3205-11ea-9dac-5e21c18796ad.PNG)

**Comment by aboba** [comment]
The problem of SVC configuration has been addressed via the `scalabilityMode` concept defined in [WebRTC-SVC](https://www.w3.org/TR/webrtc-svc/) and metadata has been added to identify the layer a frame corresponds to.  Together, these additions allow the application to change the `scalabilityMode`, or to stop or re-start sending a layer.  At this point, the only major feature not addressed is to allow target bitrates to be configured for each layer, as suggested by @orphis in https://github.com/w3c/webrtc-svc/issues/14 .

**Comment by aboba** [comment]
#187 addresses SVC. Simulcast currently is handled by creating separate encoders. In principle things like Opus FEC can be handled via codec configuration.  So we seem to have addressed most of this, with the exception of things like FEC or RED (which can be handled in WASM)?

**Comment by chcunningham** [comment]
POR: 
- SVC will be configurable (see #40)
- FEC will either be done by the app, or where codec-specific options exist, we will create code-specific config knobs
- Simulcast: out of scope, just spin up multiple encoders (or better yet, use SVC)

**Comment by chcunningham** [comment]
I don't think there's anything actionable remaining in this issue. SVC is tracked in #40. Simulcast in #44. And we've determined FEC is out of scope. Happy to have new issues filed for codec specific FEC features where demanded. Closing for now. Please reopen if I've overlooked anything.

**Comment by murillo128** [comment]
Shouldn't we allow to configure opus in-band fec?

https://www.opus-codec.org/docs/html_api/group__encoderctls.html#ga5b67dc832aa46c1c2f35752c46380545

**Comment by chcunningham** [comment]
Happy to do that. I intended to leave room for that with this comment 

>
