### ISSUE TITLE
Support NV12 pixel format

### ISSUE THREAD

**Issue by zlma7001** [w3c/webcodecs#90]
NV12 is a very common pixel format which can be produced by ISP and consumed by GPU, HW encoder and hardware overlay, so support nv12 format can avoid lots of pixel format conversion and frame copies, then both the power consumption and performance will benefit in webcodecs.

**Comment by chcunningham** [comment]
FYI, this format is now supported in Chrome. I still need to add this to the spec.

**Comment by chcunningham** [comment]
Re milestone, this is an important issue but not a launch blocker. Its just an addition (not a breaking change). NV12 is already supported in Chrome and I'm confident we will definitely add it to the spec shortly.

**Comment by chcunningham** [comment]
Triage note: marked 'extension' as this is just adding a new format. Additions aren't breaking.

**Comment by chcunningham** [comment]
Closing old bug: this is now specified and implemented in Chrome
https://w3c.github.io/webcodecs/#dom-videopixelformat-nv12
